### ISSUE TITLE
Data storage options

### ISSUE THREAD

**Issue by nielsdrost** [NLeSC/guide#102]
Question for a project from @mkuzak:

> Do we have a place to put big files. I have 160GB vm image that I need to archive. Any solution?

We should put the answer in the guide as well.

First attempt at an answer: Zenodo

**Comment by LourensVeen** [comment]
Daniel Kissling and I have been looking into this a bit for our forest fragmentation project, and once you have more than a couple tens of GB the number of places that will archive your scientific data for free begins to dry up quickly. But I guess our budgets end when the project ends, so I guess paid is also not an option...

**Comment by nielsdrost** [comment]
Could be if you can "prepay" for a decade or so, and the project included funding for this in the budget.

**Comment by nielsdrost** [comment]
One of the options is to use the 4TU data centre: http://researchdata.4tu.nl/en/home/

Cost model (from https://data.4tu.nl/account/login/?next=/user)

* Every researcher can upload up to 10 GB of data a year free of charge. For depositing additional data there is a one off cost of € 4.50 per GB.
* Researchers from the three technical universities (Delft, Eindhoven and Twente) can deposit up to 100 GB free of charge.

**Comment by LourensVeen** [comment]
Oh hey, I think we missed this one. Looks interesting, with somewhat better Terms of Use than DANS, although it has quite a few of the same issues. Will keep it in mind though, thanks!

**Comment by bouweandela** [comment]
If this is still relevant, this place on the intranet would be a good place to share this: https://nlesc.sharepoint.com/sites/home/SitePages/Access-to-Infrastructure.aspx
