### ISSUE TITLE
Default online slide sharing

### ISSUE THREAD

**Issue by nielsdrost** [NLeSC/guide#105]
The Guide currently does not have any recommendations for sharing slides.

The top suggestion seems to be slideshare.

Any other suggestions?

Does slideshare have organizations?

**Comment by jvdzwaan** [comment]
[Slideshare](https://www.slideshare.net/) now seems part of/integrated with LinkedIn. It has different account types (including non-profit/gov and university/school; see screenshot). 
<img width="493" alt="screen shot 2017-04-07 at 14 26 11" src="https://cloud.githubusercontent.com/assets/4788897/24850250/98f94eb2-1dcf-11e7-92ad-da5a59e1e0d8.png">

I'll ask @lodekulik about the nlesc linkedin account, to see whether we can use that as slideshare account. I have to say that I find the interface kind of cluttered.

Other options I found are things like [Speaker Deck](https://speakerdeck.com/) and [slidr.io](https://slidr.io/) that use github login. You have to convert your presentation to pdf before uploading (slideshare does that for you).

What exactly are the criteria we have for a slide sharing service?

- It must have organizations
- It should be free(?)

We should also look into the legal/copyright aspects. @LourensVeen any ideas?
