### ISSUE TITLE
Swap Intellectual Property and Projects

### ISSUE THREAD

**Issue by LourensVeen** [NLeSC/guide#116]
I think it makes more sense to have Projects as section 3, and Intellectual Property as section 6. Can they be swapped without messing anything up?

**Comment by jmaassen** [comment]
Swapping is fine by me, although I'm not sure if you will break any references by doing so?

**Comment by LourensVeen** [comment]
Right, no idea! I think the numbering is automatic, but I don't know if anybody has linked to these chapters from other websites, and if so if those links will break. Will have to investigate.

**Comment by bouweandela** [comment]
@jspaaks Is creating a completely new chapter layout that will make large parts of the guide usable for a wider audience, so this issue is outdated.
