### ISSUE TITLE
Keeping a CHANGELOG

### ISSUE THREAD

**Issue by jiskattema** [NLeSC/guide#117]
The release part of the guide describes keeping a log of you changes in the *CHANGELOG.md*
However, this is quite cumbersome when also following all the other recommendations like the branching model. And the information should be the same as the individual commit messages and/or pull requests.

Is there a way to automatically construct a changelog from the pull requests?

**Comment by jmaassen** [comment]
In my experience commit logs tend to be much more fine grained than the CHANGELOG (if not, you're not committing often enough ;-). So some filtering and aggregation is needed to convert one into the other.

**Comment by sverhoeven** [comment]
I would not use the commit messages, that is too much detail for a CHANGELOG. 

Issues, labels and milestones/tags could be used to generate a CHANGELOG. There are generators out there that do that.

**Comment by jspaaks** [comment]
What about just using the messages that go with the PR? I believe that's what Jisk is asking isn;t he?

**Comment by jiskattema** [comment]
yes i suggest creating a changelog from pullrequests

according to the guide:
 * commit messages short and to the point
 * pull requests more detailed explanation of changes.

**Comment by sverhoeven** [comment]
A new release is made from one or more Pull Requests (PR) which solve one or more issues. Where one PR can solve many issues or many PRs can solve a single issue.

I think listing which issues have been solved in the new release should be in the CHANGELOG.

**Comment by jiskattema** [comment]
Sure, but then we need to be more explicit what to write where.
* commit messages; short and technical
* pull requests: more a big picture motivation for changes, possibly listing issues

and then we would have:
* CHANGELOG updated (manually) on a release, summarizing both commit messages and pull request

This should then be added to the 'doing a release' part of the guide.

**Comment by jspaaks** [comment]
A policy of always having to write big picture messages when making a PR won't work for me. For instance what's the big picture when I correct a typo in a PR?

IMHO, it's better if the maintainer goes over the commit messages when preparing a release, and exstract the big picture from that. Of course, there is nothing keeping the maintainer to add items to the CHANGELOG upon receiving a PR that warrrants a big picture description. Furthermore, there is nothing keeping the maintainer from delegating this work to whoever made the PR in the first place, before merging.

As an aside, I'd like to know who consumes CHANGELOGs and for what reason?

**Comment by bouweandela** [comment]
The list of closed issues since the previous release can of course also be a good source of information for writing a changelog.

**Comment by bouweandela** [comment]
This content would be more appropriate for [The Turing Way](https://the-turing-way.netlify.app/index.html)
