### ISSUE TITLE
build failing

### ISSUE THREAD

**Issue by jiskattema** [NLeSC/guide#120]
The badge on the README shows that the build is failing.
Quickly checking the travis output shows that it fails during install of javascript stuff

**Comment by sverhoeven** [comment]
Fixed in PR #115, waiting for merge by @jmaassen

**Comment by nielsdrost** [comment]
I think this was fixed.

Also: the build is now failing due to a broken link...

**Comment by nielsdrost** [comment]
Fixed :-)
