### ISSUE TITLE
Add information on how to remove data from a GitHub repo

### ISSUE THREAD

**Issue by nielsdrost** [NLeSC/guide#125]
Via @vincentvanhees:

In case you ever accidentally put a privacy sensitive or copyright protected file in your github repository then be aware that just removing it will not remove the file from the repository history, by which you may still get into trouble. To remove it from the entire repository history and all its branches follow: 

https://help.github.com/articles/removing-sensitive-data-from-a-repository

**Comment by jspaaks** [comment]
hey Niels, 
I made code snippet, where should it go?

**Comment by nielsdrost** [comment]
@jspaaks Great! I think here https://github.com/NLeSC/guide/edit/master/software/version_control.md, though perhaps as an attachment or something if it breaks the flow of text too much. Perhaps use a gist?

**Comment by nielsdrost** [comment]
Fixed in #126
