### ISSUE TITLE
[Python] Magma/Landscape/Prospector example outdated

### ISSUE THREAD

**Issue by jvdzwaan** [NLeSC/guide#136]
Link to example for Landscape code quality tool https://landscape.io/github/NLeSC/MAGMa says the project is not being checked. 

Is there an up to date example?

**Comment by sverhoeven** [comment]
MAGMa was added to landscape a while ago, seems it has been forgotten, I tried to re-add, but failed.
I just tried to add a repo, but it also failed with https://landscape.io/github/3D-e-Chem/sygma/1

In the tour they use https://landscape.io/github/akvo/akvo-rsr as the example repo.

**Comment by bouweandela** [comment]
The text that this issue refers to appears to be no longer in the guide.
