### ISSUE TITLE
Which email to use in Code of Conduct?

### ISSUE THREAD

**Issue by mkuzak** [NLeSC/guide#14]
Use lead developer NLeSC email address or project email or corporate email.
# Comments

By @sverhoeven 
I vote for lead developer email, as it is private and easy to setup.
👍 

---

By @mkuzak
me too

**Comment by c-martinez** [comment]
Hey @wrvhage -- will the email in the code of conduct be included in the conflict resolution protocol you were working on?

**Comment by bouweandela** [comment]
This content would be more appropriate for The Turing Way
