### ISSUE TITLE
Add why to advice

### ISSUE THREAD

**Issue by bouweandela** [NLeSC/guide#150]
Explain why you should do something in addition to what you should do in order to make texts suitable for https://research-software.nl

A well written piece of advice should therefore contain the following information:
1) What, e.g. version control
2) Why, e.g. explain why version control is a good idea
3) Short how: Recommend one solution for readers who don't want to spend time reading about all possible options, e.g. at NLeSC we use git with github because ... This is where NLeSC specific info should go if it makes sense to do so, see #149.
4) Long how: also explain other options for implementing advice, e.g. list some more version control programs and/or services which we can recommend.

**Comment by egpbos** [comment]
This should go into the new Guide Guide 👍
