### ISSUE TITLE
Add google analytics?

### ISSUE THREAD

**Issue by bouweandela** [NLeSC/guide#161]
@tbkkr suggested that it would be good to have some idea of how many people are visiting the guide. Maybe we can use google analytics for this? Or do we have this enabled already?
https://docs.gitbook.com/integrations/google-analytics

**Comment by sverhoeven** [comment]
I checked with Kim in the Google Analytics dashboard and that ID is not ours.
@lodekulik can generate a ga id and we can use https://github.com/GitbookIO/plugin-ga to add our ga id.

**Comment by sverhoeven** [comment]
Seems there is also a setting (https://docs.gitbook.com/integrations/google-analytics) , but I am unable to find it.

**Comment by bouweandela** [comment]
Lode generated the id and I added it, but the build keeps failing, it looks like gitbook is having trouble with it's internet connection.

**Comment by jspaaks** [comment]
Sidenote: probably also a good idea to be transparent about what data we collect and why.

**Comment by bencomp** [comment]
If I, as an outsider and new fan of the guide, may make a suggestion: Please don't use Google Analytics, because it tracks us all over the web already. Perhaps GitBook can provide statistics? Or maybe you can run [Matomo](https://matomo.org/) in-house? Or maybe you don't actually need visitor details.

I would not be a fan of the guide if it has Google tracking on it.

**Comment by jiskattema** [comment]
I'm also not a fan of this kind of tracking software.. are there any other alternatives? do we really need this data?

**Comment by jmaassen** [comment]
For things like the guide and the RSD we need statistics like these in order to justify the time and effort being spent on them. I do agree that we should be completely transparent about this, and see if we can switch to some stand-alone solution.

**Comment by LourensVeen** [comment]
The problem is that we don't like Google tracking which sites everybody visits via the GA tracker. As I read that page, they still have the request for ga.js or analytics.js with your full IP address and the Referer header...

**Comment by jspaaks** [comment]
Hey @bencomp, thanks for the suggestion, Matomo looks promising!

**Comment by c-martinez** [comment]
@ctwhome -- maybe we can try this out?

**Comment by egpbos** [comment]
This discussion seems outdated; we don't use GitBook anymore.

However, there is a GA code in the new docsify Guide as well, but I'm not sure whether it (still) works. @VeronicaWYPang and I are trying to get access, so stay tuned.

**Comment by egpbos** [comment]
We will not use Google Analytics.
