### ISSUE TITLE
Problems with prospector under Python 2

### ISSUE THREAD

**Issue by jvdzwaan** [NLeSC/guide#162]
pylint dropped Python 2 support, which causes problems with the newest versions (>=1) of prospector under Python 2.

Under Python 2 use `pip install prospector[with_pyroma]==0.12.11`

**Comment by sverhoeven** [comment]
On https://realpython.com/python-code-quality/ [pylama](https://pylama.readthedocs.io/en/latest/) is mentioned. Could be an alternative.

**Comment by bouweandela** [comment]
Closing this, as we no longer recommend using Python 2 anyway.
