### ISSUE TITLE
legacy gitbook shut down

### ISSUE THREAD

**Issue by sverhoeven** [NLeSC/guide#164]
GitBook has a new version see https://docs.gitbook.com/v2-changes/important-differences 

Should we migrate the guide over? Stay or change to GitHub pages powered.

**Comment by jspaaks** [comment]
There was some discussion related to this in another issue...found it https://github.com/NLeSC/guide/issues/77

**Comment by bouweandela** [comment]
> We will soon shut down (beginning of 2020) GitBook legacy meaning that you need to migrate your content to GitBook v2.

from https://docs.gitbook.com/resources/gitbook-legacy

@jspaaks @c-martinez We probably need a decision on this quite soon. Since you are in charge of the guide, could one of you pick this up? I think we either need to migrate to version 2 or decide to use something else than GitBook.

**Comment by c-martinez** [comment]
In either case (migrate to version 2 or move to something else) we should plan a 'sprint' for moving things over and "dusting off" the content -- I've scheduled a meeting with @jspaaks and @jmaassen to discuss this so we will plan this sprint soon (and should have a decision on migration before such sprint.

**Comment by sverhoeven** [comment]
Gitbook is shutting down their legacy gitbooks, like our guide on 30th April 2020. 

We need to do something to keep https://guide.esciencecenter.nl/ working.

**Comment by c-martinez** [comment]
Ah, good point. Thanks for the reminder @sverhoeven .

What are our options?

The ones I can think of:
 - Upgrade to V2
 - Moving to readthedocs
 - Self hosting

Are there other platforms we could move to?

**Comment by egpbos** [comment]
GitHub Pages.

I'd go for Readthedocs or GitHub Pages, just for the sake of transferable skills, since they are both popular options in the open source world (I don't think I've seen GitBook used anywhere else than at NLeSC).

**Comment by sverhoeven** [comment]
Agree with @egpbos, readthedocs  seems like the best option for hosting.

We will need to convert the guide from the gitbook layout to Sphinx, Mkdocs or some other doc generator like https://docsify.js.org

**Comment by c-martinez** [comment]
@egpbos is right that readthedocs and GithubPages are more transferable.

Docsify looks nice, but I guess if we use read the docs with a good Sphinx template, it could look just as good. 

I would say lets go for ReadTheDocs. @jmaassen , @jspaaks -- do you have a strong opinion otherwise?

**Comment by sverhoeven** [comment]
I tried out docsify on a other GitBook of mine https://3d-e-chem.github.io/tutorial, it was not a lot of work, do you mind if I make a docsify PR for the guide.

**Comment by c-martinez** [comment]
Sure, go ahead!

**Comment by sverhoeven** [comment]
https://github.com/NLeSC/guide/pull/202 PR completed, please review if acceptable.

**Comment by sverhoeven** [comment]
Bump, can #202 be merged?

**Comment by bouweandela** [comment]
> Configure guide.esciencecenter.nl to point to GitHub page

Is this something you can do? I don't think I know how to do this.

**Comment by sverhoeven** [comment]
Configuration of domain is 2 step process
1. [ ] Configure repo for custom domain
1. [ ] In our dns provider we need to point, I need to do this.

**Comment by sverhoeven** [comment]
I changed the CNAME of guide.esciencenter.nl from `www.gitbooks.io.` to `nlesc.github.io.`.
Next is to wait for DNS changes to propagate.

On https://github.com/NLeSC/guide/settings I have to wait to check `Enforce HTTPS`.

**Comment by sverhoeven** [comment]
For me https://guide.esciencecenter.nl/ shows the docsify version (recognizable by green github dog's ear)

Is it working for others?

**Comment by LourensVeen** [comment]
Works for me, nice job!

**Comment by tbkkr** [comment]
Works, nice!

**Comment by bouweandela** [comment]
Thanks @sverhoeven!

**Comment by bouweandela** [comment]
I think that the only thing that still needs to be done is cancel our subscription to GitBook (50 euros a month) and then this issue can be closed? @sverhoeven @nielsdrost

**Comment by nielsdrost** [comment]
Agree the new guide looks nice!

I made a new issue in Office-IT to drop GitBook.

To close this issue we still needs the links to Gitbook to be removed from the frontpage of the guide, I think.

**Comment by bouweandela** [comment]
Links have been removed in the pull request linked above.
