### ISSUE TITLE
Add MoSCoW method for requirements

### ISSUE THREAD

**Issue by mkuzak** [NLeSC/guide#17]
By @LourensVeen
MoSCoW is a simple method which gives a bit of structure to the list of requirements. We should use it.
# Comments

By @mkuzak
I think that should be part of roadmap. Currently we're missing ROADMAP.md we should think about it and I this would go into this file in my opinion.

---

By @blootsvoets 
I think what Lourens means is to use this MoSCoW method on the estep-checklist. In my opinion, if we use Github milestones correctly (I don't think any NLeSC project does), there isn't that much need for ROADMAP.md. Of course, in milestones we could also use the MoSCoW method.

---

By @mkuzak
I think Lourens meant MoScoW for the software. At least that's what I can tell from the file changes in pull request. @LourensVeen please correct :).
I do think roadmap becomes important when you want to attract external contributors. People will want to know that the project is going the same direction they are interested in if they're going to invest their time in it.

---

By @LourensVeen
No, I meant using MoSCoW for the software, not for the checklist. Although of course we could apply the checklist to the checklist and ascend to a meta-recursive state of zen, but then we need to order Mateusz some wireless headphones so he can float through the office unrestrained by cabling.

Anyway, my main point is that MoSCoW is a nice tool for organising requirements, and that we should use it, mainly at the beginning of a project and at any re-plannings along the way.

The list of MoSCoW-prioritised requirements could be on the project manager's laptop, but why not make it part of the project documentation? As Mateusz says, it's nice for (potential) external contributors to have an idea of where we are going.

---

By @jiskattema

You can easily do it in github with Labels; just standardize on the naming. 'Must' = blocker, 'Should' = highly desired / milestone, 'Could' = potential feature, 'Would' = nice to have, but dont wait for it.

Or, an alternative interpretation:
Must: certain
Should: likely
Could: not likely
Wont: definitely not

---

By @LourensVeen
Well, but then you'd need some rather broad issues, which would be open for the duration of most of the project. Maybe it's better to have that separate from the day-to-day work?

**Comment by mkuzak** [comment]
By @LourensVeen
  
software/documentation.md#well-defined-functionality 
-Ideally in README.md
+Ideally in README.md. Make sure to also document what it *doesn't* do. Use the
+[MoSCoW method](https://en.wikipedia.org/wiki/MoSCoW_method) to prioritise functionality.

**Comment by c-martinez** [comment]
@LourensVeen, is this issue still relevant? I am not exactly sure what was meant by it and where would this fit in the guide.

**Comment by LourensVeen** [comment]
The point of this was that it is a good idea in any project to explicitly keep track of the scope of the project, and one way to do that is to create a list of requirements and organise them according to the MoSCoW principle. I thought that this could help to communicate clearly with a PI about what we will and won't do, so I made an issue to add it to the guide. But I had just joined the Center and didn't realise that our projects were much less formal than that.

We are now partially introducing Agile/SCRUM. A MoSCoW-organised list of requirements isn't that different from a backlog as kept by the product owner, and serves the same purpose. So maybe someone could write something about that if they wanted to.

**Comment by c-martinez** [comment]
I guess either MoSCoW list, backlog, or some other method are equally valid and it would be up to whoever is running the project to decide what works best for them? In that sense, maybe we do not need to be prescriptive about it?

I suggest we close this issue (and maybe address the broader issue of "Alternatives to keep track of project scope" in a section of the guide / The Turing Way?

**Comment by LourensVeen** [comment]
Sounds good, closing...
