### ISSUE TITLE
Build broken due to link checker

### ISSUE THREAD

**Issue by jvdzwaan** [NLeSC/guide#176]
I merged a pull request, and now the build is broken, because the link checker fails. It mainly fails because it doesn't like https://www.gitbook.com/, which seems to work fine when I open it in a browser. Any ideas on how to fix this?

**Comment by bouweandela** [comment]
I don't think it's related to the pull request you merged. Let's just wait a few days to see if the issue goes away.

**Comment by jspaaks** [comment]
FWIW, when I run the link checker locally following instructions from CONTRIBUTING.md, I have a handful of broken links (all but 2 are correctly reported as broken)
My versions
```bash
git log --pretty=oneline -n 1
0b6f0dc9067bb26d51e4faf6714308776f835629 (HEAD -> master, origin/master, origin/HEAD) Merge pull request #175 from NLeSC/pypi-nlesc-co-owner
$ node --version
v8.9.4
$ npm --version
5.6.0
$nvm --version
0.31.6
```
These are reported broken:
└─BROKEN─ http://cruisecontrolnet.org/projects/ccnet/wiki/CCTray_Download_Plugin (BLC_UNKNOWN)
├─BROKEN─ http://blog.oio.de/2014/04/04/internet-explorer-11-source-map-based-debugging/ (ERRNO_EHOSTUNREACH)
├─BROKEN─ https://addons.mozilla.org/en-US/firefox/addon/firebug/ (HTTP_404)
└─BROKEN─ http://continuum.io/downloads (HTTP_522)
├─BROKEN─ http://www.prace-ri.eu/best-practice-guide-gpgpu-january-2017/#gpu_programming (BLC_UNKNOWN)
└─BROKEN─ http://www.prace-ri.eu/IMG/pdf/Best-Practice-Guide-GPGPU-1.pdf (BLC_UNKNOWN)
├─BROKEN─ http://ggplot2.org/ (HTTP_404)
├─BROKEN─ http://www.stack.nl/~dimitri/doxygen/ (HTTP_403)
├─BROKEN─ https://blog.esciencecenter.nl/irregular-data-in-pandas-using-c-88ce311cb9ef?gi=23ebfce3ae77 (HTTP_409)
├─BROKEN─ https://www.procolix.com/ (BLC_UNKNOWN)
└─BROKEN─ https://www.esciencecenter.nl/project-calls (HTTP_404)
