### ISSUE TITLE
Explain how to upload releases from CI to pypi

### ISSUE THREAD

**Issue by jvdzwaan** [NLeSC/guide#177]
Save time by not having to upload releases to pypi separately!

https://docs.travis-ci.com/user/deployment/pypi/

https://medium.com/@mikkokotila/deploying-python-packages-to-pypi-with-travis-works-9a6597781556

**Comment by bouweandela** [comment]
It might be nice to also support this for CircleCI:
https://circleci.com/blog/continuously-deploying-python-packages-to-pypi-with-circleci/
