### ISSUE TITLE
Link to: The Turing Way is a lightly opinionated guide to reproducible data science?

### ISSUE THREAD

**Issue by bouweandela** [NLeSC/guide#178]
https://github.com/alan-turing-institute/the-turing-way

**Comment by c-martinez** [comment]
Apparently this is happening -- opening issues here: https://github.com/nlesc-sigs/software-sustainability/issues

**Comment by mkuzak** [comment]
We decided we are going to migrate the parts of the guide which are generic to the Turing Way. The issues relevant to migration created so far are in the [S^3 sig](https://github.com/nlesc-sigs/software-sustainability/issues) with label Guide Sprint. From now on the issues connected to this topic will be in this repository with the label "Turing way". I'm closing this issue.
