### ISSUE TITLE
checklist divided by events in the project

### ISSUE THREAD

**Issue by mkuzak** [NLeSC/guide#19]
Example of events:
- first user
- first contributor (pull requests)
- first external collaborator (push access)
- first release
- first dissemination

developer should make sure those the relevant checklist items are implemented at the time of those events

We should create an additional checklist page with items matching those events.

**Comment by nielsdrost** [comment]
For reference, we once did this exercise and ended up with a "3 phase" checklist. This did not make it to the guide (yet), but lives in the git history of the estep-checklist repo here:

https://github.com/NLeSC/estep-checklist/blob/b6b499275ba97805b855ccdc53f2b990a3a017b4/checklist-matrix.md

**Comment by mkuzak** [comment]
Yes, I know, but we discussed it with @sverhoeven today and we'd like to give it one more try. It does feel more connected to how we work and gives less excuses for not doing things.

**Comment by nielsdrost** [comment]
Yes, good idea. I think it also highly depends on personal preference. Perhaps we could even make several different versions of the checklist catering to different ways of working / personalities :-)

Anyway, this is definitely an unsolved problem, so keeping previous attempts floating around hopefully helps for inspiration :-)

**Comment by nielsdrost** [comment]
Also, sorry, missed pull request #16 with exactly this content in it ;-)

**Comment by bouweandela** [comment]
This is now part of the guide.
