### ISSUE TITLE
conda vs. pip -- can result in big difference in performance. 

### ISSUE THREAD

**Issue by florian-huber** [NLeSC/guide#192]
So far I was using pip and conda side-by-side. But it seems as if for some packages performance can be affected quite a bit by which way you choose!
(such as numpy, scipy, tensorflow)
--> https://towardsdatascience.com/stop-installing-tensorflow-using-pip-for-performance-sake-5854f9d9eb0c

Maybe good to mention in the Python guide?

**Comment by egpbos** [comment]
The top response under that post shows a way to get an MKL enabled pip package :) It's not the package manager, it's the packages that matter in the end. For me, the best workflow is to use conda for the basic environments and install from pip what is not in Conda (which is still quite a lot; pypi is still the default option for most of the Python community), but YMMV and also it may change over time (maybe tomorrow the pip package is faster for some reason). So I personally think this topic a bit too detailed and dynamic to properly maintain on the Guide.

**Comment by florian-huber** [comment]
Ok, thanks @egpbos . That indeed makes it a look much less straightforwards (and confusing to add to the guide).
