### ISSUE TITLE
DOI for the guide

### ISSUE THREAD

**Issue by c-martinez** [NLeSC/guide#193]
The guide itself does not have a DOI -- shouldn't it?

Discussion point: is it sufficient to connect the repo to zenodo? Or can we somehow link the DOI to the gitbook built, so people visiting https://guide.esciencecenter.nl/ can easily find the DOI (and cite the guide!)

**Comment by jvdzwaan** [comment]
I think having a DOI for the guide would be useful. Not sure whether many people will cite it, but we should practice what we preach, right?

For code repos the Zenodo DOI badge can be added to the readme, we can do something similar for the guide (we should put the badge in the guide, not just in the readme).

For linking the Zenodo page to the actual guide, we could put a link on top of the release description, which is added as a 'readme' on the Zenodo page.

I don't think the guide has 'official' releases, has it?

**Comment by c-martinez** [comment]
Indeed practice what we preach. Yes, I guess including the zenodo badge maybe in the introduction to the guide is one solution -- if nobody has a better suggestion, let's go for that.

Indeed, the guide does not have official releases... yet. But we will need to make releases in order for zenodo to pick up new versions. Maybe we don't need a new release with every commit, but if we make releases every 6 months or so, we can have a kind of historical record of guide.

**Comment by jspaaks** [comment]
Myeah not super convinced but anyways, enabling the zenodo-github integration and making releases will generate dois that point to the source for the gitbook, not the gitbook itself. 

Unassigning myself ftm.

**Comment by c-martinez** [comment]
So... the better option would be to produce a PDF and upload that PDF as the "release version" to Zenodo? It sounds like too much manual work, but perhaps it could be automated.

The guide includes a link to the source anyway, so people can always go back to the source to contribute.

## Automation
Apparently you can [build a PDF from gitbook](https://gist.github.com/xf-/2b759814a9aef1c9c88d9574b10b8493) and [uploaload items via zenodo api](https://developers.zenodo.org/#deposition-actions).

**Comment by c-martinez** [comment]
Automation of deployment is technically doable.

Couple of questions:
 - Who should own the item in Zenodo (do we have a zenodo nlesc account?)
 - Who should be listed as author? At the moment this needs to be entered manually in Zenodo (which is not ideal).

@jmaassen -- do you have an opinion on the topic?

**Comment by jmaassen** [comment]
As far as I can tell zenodo always uses individuals as authors, not organizations?

For software we use the CFF to generate an .zenodo file that contains all author information. Would something similar work for the guide?

**Comment by c-martinez** [comment]
I think you are right about zenodo using individuals as authors. I can just register it with my account, authors and affiliations are acknowledged anyway.

As long as we have an updated CFF file, we could pull all the metadata from there.

**Comment by bouweandela** [comment]
Citation file added in https://github.com/NLeSC/guide/pull/194

**Comment by c-martinez** [comment]
Thanks!
TODOs:
 - [ ] Add initial version of the guide on Zenodo.
 - [ ] Add travis build code to auto-push to Zenodo on new release.

**Comment by c-martinez** [comment]
Zenodo DOI is now available, 10.5281/zenodo.4020564
