### ISSUE TITLE
Merge code of conduct repo into guide

### ISSUE THREAD

**Issue by egpbos** [NLeSC/guide#199]
The text in the [code of conduct repo](https://github.com/NLeSC/code-of-conduct) readme should be merged into the Guide and the repo itself should then either be deleted (if no one references it anywhere) or changed into a redirect/link to the relevant Guide page. Previous discussion at https://github.com/NLeSC/Office-IT/issues/603

**Comment by mkuzak** [comment]
I would be in favour of keeping this repository a place for CoC text. Maybe making more viewer friendly GH pages that we can refer to. I want to have a place that I can point to when for example hosting nl-rse meetup or run a workshop. The guide does not work well for this purpose. The guide is for engineers, not members of the community. There may be a copy of CoC in they guide, as a template for the project. There is other issue, and I should create one, probably on the CoC repo, how do we enforce the CoC? The CoC text does not mention how one could report the violation and what is the procedure, except for the in person/workshop setup. Even in the in person setup, there needs to be the way to contact someone else than the host, in case the host is the abuser. And there is more to this, that I will try to summarise in the other issue

**Comment by egpbos** [comment]
Regarding the latter questions: this is all standard CoC stuff, so I'm sure there are templates available. We have a setup like that for PyData Groningen as well (except that we didn't act on it yet, but the idea of having someone to go to in case of incidents, etc).

About the first thing: of course you can always keep it a separate repo. The question is: should it also be part of the Guide? I don't know, for me either way is fine, just something to think about.

If it becomes part of the guide and you still want a separate repo for events, does it make sense for you to maintain that repo yourself? Or can we just join some other organizations in using a standardized CoC, which would save a lot on maintenance?

**Comment by mkuzak** [comment]
> Regarding the latter questions: this is all standard CoC stuff, so I'm sure there are templates available. We have a setup like that for PyData Groningen as well (except that we didn't act on it yet, but the idea of having someone to go to in case of incidents, etc).
> Yes, this is standard stuff. Yes, we are using the template, Contributors Covenant. You did not act on it, because there were no reports? Did you have a documented process how to act on it? Did the CoC committee know what to do?

**Comment by egpbos** [comment]
> You did not act on it, because there were no reports? Did you have a documented process how to act on it? Did the CoC committee know what to do?

We just started and haven't had a chance to set up the committee :) But also no reports, no. Anyway, off topic here ;)

**Comment by mkuzak** [comment]
> About the first thing: of course you can always keep it a separate repo. The question is: should it also be part of the Guide? I don't know, for me either way is fine, just something to think about.

I think the Guide should contain the template for CoC that one can drop in their repo and explanation how to rollout CoC in their project. I can write it up, I'm currently looking into it.

**Comment by mkuzak** [comment]
> > You did not act on it, because there were no reports? Did you have a documented process how to act on it? Did the CoC committee know what to do?
> 
> We just started and haven't had a chance to set up the committee :) But also no reports, no. 

well, if you did not have a committee, were would the reports go?

> Anyway, off topic here ;)

Yes :)

**Comment by egpbos** [comment]
It's a personal effort, I'm not doing it as an NLeSC activity, so things go as fast (or slow) as my limited free time allows :)

**Comment by mkuzak** [comment]
> If it becomes part of the guide and you still want a separate repo for events, does it make sense for you to maintain that repo yourself?

I would like to have a single eScience Center CoC page that I can point to for most of the events.

> Or can we just join some other organizations in using a standardized CoC, which would save a lot on maintenance?

I'm not sure how that would work. We do want to use standardised CoC but we cannot leave the implementation to some other organisation. Our spaces and community is our responsibility.

**Comment by bouweandela** [comment]
This looks like an outdated discussion. Please feel free to re-open if it is still relevant.
