### ISSUE TITLE
Add language chapter on bash

### ISSUE THREAD

**Issue by bouweandela** [NLeSC/guide#215]
I noticed we're missing a chapter on bash, I'll try to write something down because I think this is an essential skill for any eScience Engineer.

**Comment by SarahAlidoost** [comment]
There is a nice tutorial on Software Carpentry about Unix/shell http://swcarpentry.github.io/shell-novice/
This might be helpful.

**Comment by mkuzak** [comment]
I agree that the Unix Shell (not only Bash) is an essential skill for every engineer. There are a lot of resources about the shell around on the internet and should not replicate that. We should be pointing to the resources we believe are of high quality and focus on emphasising the skill we believe are most useful.

**Comment by egpbos** [comment]
The point @mkuzak makes between parentheses (not only Bash) made me think. I'm not sure how essential specifically Bash or Unix shell is really. It is used a lot in some places, true, but so is Python or Javascript, would we call that crucial? I think there are a few skills to disentangle here:

1. Shell scripting (through your favorite language; (ba)sh, csh, powershell)
2. Use and knowledge of specific shell tools; the "Unix" or GNU (or equivalent BSD) toolset or some kind of (unknown to me) toolset in Windows. So `ls`, `sed`/`awk`, `grep`, `sort`, `cut`, etc., which are all shell-independent. But also slightly more shell-dependent things like piping/combining commands and things like `xargs` for parallelism.
3. Experience in using the tools effectively and efficiently for textual data wrangling.

To point 1. I would say: let's not push for any specific language (you can even do shell scripting through Python if you like).

Regarding parts 2 and 3: knowledge of shell tools can be useful, but the things they can do can also be done in text editors or data analysis packages and I wouldn't say it's essential for every engineer to do them in a shell. I can see the value, of course (I use them myself as well), but I'm not sure how much effort we should put into writing a guide for what is essentially one specific toolkit for text wrangling. Especially given what @mkuzak already mentioned, that the web is chock-full of guides on this specific topic already, from universities and many others.

**Comment by Peter9192** [comment]
For point 1: What about some best practices? There's a difference between a shell script anyone can write, and a shell script that we want to vouch for.

**Comment by mkuzak** [comment]
I'd love the concise set of shell scripting best practices. Again I'm pretty sure there is something out there that we can reuse and tweak.

**Comment by bouweandela** [comment]
Indeed my intention was not to write a very lengthy chapter, just something that points new engineers in the right direction.

> There are a lot of resources about the ... around on the internet and should not replicate that. We should be pointing to the resources we believe are of high quality and focus on emphasising the skill we believe are most useful.

@mkuzak I think this is what we want for the entire guide, not just for a chapter on shell scripts

> but so is Python or Javascript, would we call that crucial?

@egpbos I think Python is a crucial skill for the majority of the engineers working at the eScience Center and so is the ability to efficiently use a shell to interact with your computer.

**Comment by SarahAlidoost** [comment]
I think the scope of this issue is more about Unix tools (as mentioned in the second item by @egpbos ). And this knowledge can be necessary for engineers, especially while working with remote servers.
