### ISSUE TITLE
Support downloading as PDF again

### ISSUE THREAD

**Issue by bouweandela** [NLeSC/guide#216]
A user has asked if it would be possible to download the guide as PDF. Previously this was possible, but the option disappeared when we switched to the new build system. A package that supports converting to PDF is https://github.com/meff34/docsify-to-pdf-converter. I managed to create a PDF locally by following the steps in the readme of that package and changing the paths in _sidebar.md to relative paths, but I'm not sure how to add this as a download button to the site. @sverhoeven Would you know a way to add a download as PDF button again?

**Comment by sverhoeven** [comment]
I can switch from Travis-CI to GH Actions and generate the PDF on push and upload the PDF as an [artifact](https://help.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts). I should be able to add a link from the README.md to the artifact.

**Comment by sverhoeven** [comment]
Seems I can generate the PDF at https://github.com/NLeSC/guide/actions/runs/116815738, but the link to the PDF only works when I am logged in and it's inside a zip file.

**Comment by bouweandela** [comment]
It looks like the file will also [be deleted after 90 days](https://help.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts#downloading-or-deleting-artifacts), so maybe a different hosting solution would be a better choice.

**Comment by c-martinez** [comment]
PDF files are generated on new releases, and deposited in [zenodo](https://doi.org/10.5281/zenodo.4020564).
