### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by egpbos** [NLeSC/guide#22]
Before I start a commit-war, let's do a simple religious war in this issue ;)

There are a few things I don't like about the latest version of the Python guide:
1. Conda seems to be the non-recommended option. Imho Conda is currently far superior to pip + virtualenv. One important thing to note is that **one can use pip inside a Conda enviroment as well**. Packages that are not included in Conda can still simply be installed with pip. This is common practice, especially when developing. It makes no sense whatsoever to compile numpy and scipy every time you need a new virtualenv. Until pip gets **at least** a build cache (preferably just a binary download like Conda, but okay, a build cache would already be a great improvement), I think we should advocate using Conda. For saving on power and the environment, if nothing else.
2. I know some people like PyCharm, and I guess I can live with that ;) I don't like IDEs at all though. I generally find recommending editors a very tricky subject, actually. Unless there is like 90% agreement within a community that a tool is indispensable (like pip), I'm not sure why we should talk about it (unless it's clearly superior, like conda :D). I don't think anybody will visit our guide to get advise on editors, they will simply Google it (I would); and anyway, the editor is such a basic need that people don't need guidance on it. Package management is different of course, since a beginner wouldn't know that there is such a thing at all, so there it helps to have the "Googleable terms" collected in a single place.
3. Multiprocessing is a mess in Python. I think we should just put it plainly like that. For sure, recommending just one package totally gives the wrong picture. The alternative to just letting people find out on their own is to list many more packages. For instance, iPython/Jupyter also has parallel stuff built in, there's things like RabbitMQ, we have Noodles, you could build a C module or use Numba or PyCUDA, etc. My preference would be to just state that Python is not really built for it.
4. About iPython: clearly this is a superior interpreter, but that's about it. What grew out of it is also very interesting: **Jupyter notebooks**. Jupyter has become language agnostic, but still, it is a very powerful Python tool for interactive analysis, education, communication. Should mention this.

I can write a pull request soon incorporating these aspects. Before doing so, just want to make sure that it's not going to be rejected ;) Shout out to previous contributors: @jvdzwaan @blootsvoets @nielsdrost

**Comment by jiskattema** [comment]
1. no opinion, i prefer pip + system packages above conda, but ok.
2. only mention editors if they are really standard (90+%), or offer amazing features for the language (code introspection, completion, etc). This to make real beginners aware of other options than Word or VisualStudio. For the rest, i agree with your point. I'm a (passionate) vim + plugins user.
3. agree, but after stating it is not built for it, we really should list our own estep stuf for it.
4. ipython should be the default interpreter for beginners, and Jupyter stuff is really great to show and  demo your code. We should mention this, and the way jupyter notebooks in github work.

**Comment by wrvhage** [comment]
I also prefer pip in daily use, BUT conda is easier to install from scratch, e.g. for use in dockers.

Willem

| Dr. Willem van Hage | Technology Lead Data Management and Analytics | email: w.vanhage@esciencecenter.nl<mailto:w.vanhage@esciencecenter.nl> |
| Netherlands eScience Center | Science Park 140 | 1098 XG Amsterdam | The Netherlands | www.nlesc.nl<http://www.nlesc.nl/> |

On 16 Jun 2016, at 09:06, Jisk Attema <notifications@github.com<mailto:notifications@github.com>> wrote:


  1.  no opinion, i prefer pip + system packages above conda, but ok.
  2.  only mention editors if they are really standard (90+%), or offer amazing features for the language (code introspection, completion, etc). This to make real beginners aware of other options than Word or VisualStudio. For the rest, i agree with your point. I'm a (passionate) vim + plugins user.
  3.  agree, but after stating it is not built for it, we really should list our own estep stuf for it.
  4.  ipython should be the default interpreter for beginners, and Jupyter stuff is really great to show and demo your code. We should mention this, and the way jupyter notebooks in github work.

**Comment by jhidding** [comment]
1. Conda / miniConda / vanilla pip+virtualenv should all work. There is no reason to advise one or the other in NLeSC context, except that Conda is easier to install from scratch because Numpy.
2. PyCharm is nice in some ways; so we can mention it.
3. Agree.
4. Bit of terminology: IPython is not an interpreter but a Repl (Read-Eval-Print-loop). Underneath is the same Python interpreter. These days IPython and Jupyter(console) are the same thing. So just refer to it as the single great Jupyter.

**Comment by egpbos** [comment]
It's not just about pip (I guess everyone uses that), it's the combination with virtual environments. You can use pip as root as well, or use it with `--user` to install things in `~/.local`. That's all fine, you don't really need conda then.

The main issue here is that for development it is very convenient to use a virtual environment; not just for your own packages, but for others as well. I found that the quickest way to set up and manage such environments, at this moment, is to use:

* conda for the virtual environment
* conda for most packages
* and pip (inside the conda environment!) for the rest (development versions, experimental packages, etc.)

Previously, this was:

* virtualenvwrapper for the venv
* pip for all packages

The main reasons to advocate the "conda (+ pip)" setup over the "virtualenv(wrapper) + pip" one is speed and useless waste of resources due to recompiling (mainly numpy and scipy) for every new enviroment.

**Comment by blootsvoets** [comment]
1. Many pip packages have a pre-built [wheel](http://pythonwheels.com), at least the packages you mention. On at least scipy and numpy, wheels for multiple OSes are present (see e.g. https://pypi.python.org/pypi/numpy/1.10.2 for a list of numpy wheels.) I don't mind using conda if I can then just use pip+virtualenv, but for me the conda step is overkill. Perhaps just remove opinionated text from that part of the guide?
2. Agree on editors. Maybe we can just mention for people that prefer an IDE that PyCharm is used frequently within NLeSC. Perhaps Vim with a list of python-relevant plugins would be good to mention?
3. A disclaimer is fine.
4. sure.

**Comment by mkuzak** [comment]
Why not write what are the options, their advantages (e.g. conda easy to install) and disadvantages (e.g. conda does not have all packages and you'll need to use pip too) and let a reader decide. This guide is for us and if I read it I want choices selected by eScience Engineer not random person from the internet. As for editors/IDE we should list those which have great support for particular languages (e.g. PyCharm has great debugging options) and if you're a passionate Vim user you will not even read this section.

**Comment by egpbos** [comment]
@blootsvoets, I did not know about wheel actually, seems nice. However, if I understand correctly, it only prebuilds things for Windows and macOS, not Linux, so that should be added. Perhaps wheel could get its own header in the guide?

**Comment by jvdzwaan** [comment]
Thanks for starting this discussion. I already started working on a new version of the Python guide (branch update-python). So, please have a look at that one, and feel free to adjust the text.

**Comment by blootsvoets** [comment]
@egpbos, it also prebuilds for Linux, see https://pypi.python.org/pypi/numpy/1.10.2, it has a lot of `manylinux` wheels. I see this is a recent development: https://github.com/pypa/manylinux. It requires pip version >= 8.1

**Comment by egpbos** [comment]
Ah right, cool :) The pythonwheels site and the official wheels docs still mention that Linux wasn't supported, confusing. Damn, now I'll have to switch again... :P

**Comment by jvdzwaan** [comment]
I think all points of discussion in this thread have been addressed (at least in a first version kind of way), so I'm closing this issue. 

Feel free to open new issues (or pull requests) if you think something should change.
