### ISSUE TITLE
update Python testing section

### ISSUE THREAD

**Issue by egpbos** [NLeSC/guide#220]
The Python testing section imho can be trimmed a bit and needs to be updated. The current section reads:

```md
## Testing

* [pytest](https://docs.pytest.org/) is a full featured Python
testing tool. You can use it with `unittest`.
[Pytest intro](http://pythontesting.net/framework/pytest/pytest-introduction/)
* [Using mocks in Python](http://www.drdobbs.com/testing/using-mocks-in-python/240168251)
* [unittest](https://docs.python.org/3/library/unittest.html) is a
framework available in Python Standard Library.
[Dr.Dobb's on Unit Testing with Python](http://www.drdobbs.com/testing/unit-testing-with-python/240165163)
* [doctest](https://docs.python.org/3/library/doctest.html) searches for pieces of text that look like interactive Python sessions, and then executes those sessions to verify that they work exactly as shown. Always use this if you have example code in your documentation to make sure your examples actually work.

Using `pytest` is preferred over `unittest`, `pytest` has a much more concise syntax and supports many useful features.

Please make sure the command `python setup.py test` can be used to run your tests. When using `pytest`, this can be easily configured as described in the [`pytest` documentation](https://docs.pytest.org/en/latest/goodpractices.html#integrating-with-setuptools-python-setup-py-test-pytest-runner).
```

I would suggest removing `unittest` altogether, since we recommend `pytest`. We don't need to list all alternatives.

The bottom paragraph should be removed altogether, since the `test` command in setuptools has been deprecated: https://github.com/pypa/setuptools/pull/1878 https://github.com/pytest-dev/pytest/issues/5534

Any objections, additions or other thoughts? If not, I'll make a PR or if someone else wants to do it, by all means :)

**Comment by egpbos** [comment]
The second to last paragraph can also be removed if we remove `unittest` from the list.

**Comment by bouweandela** [comment]
I mostly agree, though as far as I know there is no substitute for `unittest.mock` in pytest. You can use that nicely with pytest through the `mocker` fixture provided by the [pytest-mock](https://pypi.org/project/pytest-mock/) plugin though.

**Comment by LourensVeen** [comment]
I didn't know about pytest-mock, but I've been using MagicMock and patch for years with pytest, works fine.

Maybe a note should be added that there are many useful pytest plug-ins in general? I use several for linting, like pytest-pycodestyle and pytest-mypy, and it's quite convenient. If you're new to pytest, that may be nice to know.

**Comment by bouweandela** [comment]
`pytest-flake8`, `pytest-cov`, `pytest-html` and `pytest-xdist` (or `pytest-parallel`) might also be nice to mention.

**Comment by bouweandela** [comment]
More plugin info: https://docs.pytest.org/en/stable/plugins.html

**Comment by LourensVeen** [comment]
Ah yes, I can recommend pytest-cov and pytest-xdist. The latter was useful in Cerise, where I had to build Docker images as part of the tests, and with xdist that could be done in parallel, which sped things up a lot.

**Comment by egpbos** [comment]
Ok, great comments, I tried to sum it all up in an updated section, please check it out in #219. Accidentally pushed it to that PR branch, which in the end I think is fine, because it was only a link fix and wasn't merged yet anyway.
