### ISSUE TITLE
eScience branding

### ISSUE THREAD

**Issue by c-martinez** [NLeSC/guide#221]
@ctwhome suggested adding some eScience center branding to the guide.

Todo:
-  [x] eScience center logo on the search bar
-  [x] eScience colour scheme
-  [x] Download button for PDF version of guide (see #217)
-  [ ] Welcome image on landing page (turing-way style)

**Comment by ctwhome** [comment]
![image](https://user-images.githubusercontent.com/4195550/92580578-d6213600-f28e-11ea-8696-b001b06b735a.png)

**Comment by ctwhome** [comment]
please check the pull request https://github.com/NLeSC/guide/pull/227

**Comment by bouweandela** [comment]
Closing this since it is mostly done.
