### ISSUE TITLE
Include JAMStack and a visual diagram for the different kinds of web technologies stack

### ISSUE THREAD

**Issue by ctwhome** [NLeSC/guide#230]
JAMStack (https://jamstack.org/) is a new web architecture that delivers best performance by compiling dynamic content into 
static content that can be hosted easily free hosting services like GitHub Pages, NetlifyCMS, or firebase hosting without additional costs and still being updated via headless CMS (Databases, MD files or third party services like Hasura, NetlifyCMS or PrismicCMS among others)
![image](https://user-images.githubusercontent.com/4195550/98357399-6f699000-2025-11eb-9ee6-1ac0c3675c37.png)

**Comment by egpbos** [comment]
@ctwhome is this still relevant? Do you want to create and maintain a web technologies chapter?

If so, please do some research, brainstorm with a few others about what could be the content of such a chapter (preferably content that doesn't get outdated every week), and discuss it further here before writing actual text.

If not, please close the issue :)

**Comment by ctwhome** [comment]
it is relevant, although I am unsure if the message is explained well enough to be understood by anyone who is not familiar with web architecture. In any case, it would require some work. I would propose to close it for now and reopen it in case we work on a newly renovated Application Development with Web technologies.

**Comment by egpbos** [comment]
Sounds good! When we start that discussion (I think it could be a very useful chapter indeed!) I'd be interested to also explicitly consider **research** applications and the constraints that brings, like privacy, precise control (without too much effort), easy coupling to databases (for later analysis of gathered data for instance), usability/trust, etc. That could help people make more targetted choices, perhaps (maybe not, I'm not an expert, but let's see! :) ).
