### ISSUE TITLE
Links in guide content should be checked

### ISSUE THREAD

**Issue by nielsdrost** [NLeSC/guide#24]
Somewhat like the links in the software site, we should check if the links in the guide are (still) valid.

**Comment by sverhoeven** [comment]
Created a Travis-CI config to check links see https://github.com/NLeSC/guide/tree/broken-link-checker branch.

It could be triggered by push or run every night using https://nightli.es/

For example output see [blc.out.txt](https://github.com/NLeSC/guide/files/320495/blc.out.txt)

**Comment by LourensVeen** [comment]
Cool! I have some broken links... Now to make it perfect, it should make an issue for each newly broken link, and assign the maintainer of the section it's in :-).

**Comment by nielsdrost** [comment]
This code is still in a branch. Could we merge it?
Travis now also supports "cron" jobs, so no need for nightly tricks any more.

**Comment by sverhoeven** [comment]
A weekly cron has been configured on Travis-CI with build on Push and Pull Request disabled.

**Comment by nielsdrost** [comment]
Awesome!
