### ISSUE TITLE
Update software citation section

### ISSUE THREAD

**Issue by c-martinez** [NLeSC/guide#248]
An [update to software citation chapter](https://github.com/alan-turing-institute/the-turing-way/issues/2056) is coming to the Turing way. The guide's section on software citation should be updated to point there.

**Comment by c-martinez** [comment]
The Turing way is also being updated to include software citation information (see their [issue 2056](https://github.com/alan-turing-institute/the-turing-way/issues/2056))

**Comment by bouweandela** [comment]
The current plan is to refer everyone to The Turing Way for this kind of generic information and remove our content. eScience Center specific information on project management can be put on our intranet page on projects: https://nlesc.sharepoint.com/sites/home/SitePages/Project-procedures.aspx

**Comment by c-martinez** [comment]
Software citation chapter on The Turing Way has already been created: https://the-turing-way.netlify.app/communication/citable/citable-cffinit
