### ISSUE TITLE
Issues with conda

### ISSUE THREAD

**Issue by c-martinez** [NLeSC/guide#249]
As discussed in the software sustainability SIG, anaconda not being free can bring issues to software built by the eScience Center in terms of it being a barrier for adoption. For more details see [Software Sustainability SIG meetings](https://nlesc.sharepoint.com/:w:/s/softwaresustainability/EUk7OUbRdW1GnyYTa44EURgB9-_SWR7VUZb3bOaYD316QQ?e=YAHlX0).

At this moment, the best thing we can do is to raise awareness with our partners about what the potential issues are. Our own engineers should also be aware that publishing through Anaconda has side effects.

A section in the guide should briefly discuss this potential issues.

**Comment by egpbos** [comment]
Mention of this was added in a recent PR.
