### ISSUE TITLE
Language guide on Go

### ISSUE THREAD

**Issue by CunliangGeng** [NLeSC/guide#250]
I learned and used Go in STRAP project. It's nice to add some guide on it.

**Comment by egpbos** [comment]
Do you think this is going to remain relevant for (our) research software in the coming years? If so, please brainstorm a bit with some others on the possible contents of a chapter on this and discuss it here before writing the actual text. If not, let's close the issue.

**Comment by jiskattema** [comment]
I'm interested in this language, and use it myself sometimes.
I don't see it being used much at the Center.
Go makes a lot of sense as a 'better python', for devops and services.
So much so, that we maybe should promote it internally ; @egpbos what do the techleads think of this?

**Comment by CunliangGeng** [comment]
@egpbos This is an really old issue ;-)  Now looking back, I used Go lang in STRAP project as I had to use a Go-based framework developed by Google, adding some new functions and compiling it to executable. This is the only experience I had on Go. Because of this, I don't have enough info to judge if it's still relevant for future projects.

**Comment by egpbos** [comment]
If someone wants to work on this, feel free to reopen, but for now it seems like Go is rarely used in projects so it does not seem relevant enough.
