### ISSUE TITLE
Add explicit workflow for NLeSC projects 

### ISSUE THREAD

**Issue by jmaassen** [NLeSC/guide#251]
At the moment the guide is a bit unclear / verbose / outdated on the software development workflow we use at NLeSC. There also seem to be some steps missing, and some steps seem to be optional (or a choice) when they really aren't. 

It would be good to make this more explicit, and depend less on the interpretation of the individual engineers.  

Some examples: 

- The guide links to the old IP policy (2017). There is a 2021 one.
- All repo's of software we create must be public from the start (according to the 2021 IP policy).
- Adding stuff to the RSD should be described somewhere. 
- Talking to your friendly neighborhood TechLead / GT / SIG when making big technical choices or running into problems
- ....

**Comment by bouweandela** [comment]
@jmaassen Is this something that you would still like to put in the guide? Or is the intranet a better location? E.g. https://nlesc.sharepoint.com/sites/home/SitePages/Project-procedures.aspx

**Comment by egpbos** [comment]
I think the direction we are going in is that the Guide will be about NLeSC specific advice **that is also valuable to share with the world**. NLeSC specific processes and links like the ones @jmaassen mentions should indeed be put somewhere on the intranet.

So, in my estimation, this is not going to be added. Feel free to reopen if you disagree :)
