### ISSUE TITLE
Add information about working in teams

### ISSUE THREAD

**Issue by svenvanderburg** [NLeSC/guide#254]
As far as a I know there is nothing about working in teams in the guide. We are developing https://nlesc.github.io/teamwork-for-research-software-development/. It is intended as material for a course, but it serves as a standalone guide on teamwork for research software development. 

My suggestion is to add a new section 'Best practices -> Teamwork'. We can add a small paragraph on why you would want to work in a team yes or no, i.e. what are benefits/downsides to working in a team. And for more information about how to best work in a team refer to the teamwork course. Curious to hear other thoughts? 

### What needs to be done

- [ ] Add a small section on how we do teamwork at the center to the guide. Something like 'At the eScience center our policy for teams is X'. We can reuse things from/link to our [paper on teams at NLeSC](https://collegeville.github.io/CW21/WorkshopResources/WhitePapers/structured-unstructured-teams.pdf) and the section kick-off slides. 
- [ ] Link to whatever comes out of https://github.com/alan-turing-institute/the-turing-way/issues/2207, which will be information about teamwork for a more generic crowd.

**Comment by svenvanderburg** [comment]
@c-martinez if I'm not mistaken you also had ideas about this?

**Comment by bouweandela** [comment]
There is some information on teamwork in The Turing Way: https://the-turing-way.netlify.app/collaboration/new-community.html

Are the eScience Center specific teams you're talking about, or is the advice more generic?

**Comment by c-martinez** [comment]
@svenvanderburg -- yes, there was issue #244, so it would be nice to integrate it indeed (the more generic things in the Turing Way, the more eScience specific ones, in the guide).

**Comment by svenvanderburg** [comment]
OK, sorry I didn't see that. I only searched for 'team'... 

This is the intended audience:
> The lesson is geared primarily towards people that create research software in an academic setting, however the lesson is most likely also useful for anyone trying to work on a team in scientific projects. Finally we hope that anyone wanting to get better at working in teams can learn something from this lesson.

So then maybe it is better to add it to the Turing way instead of the guide?

**Comment by c-martinez** [comment]
Yes, I think so. Maybe an entry in the guide (pointing to the turing way) would be suitable saying "At the eScience center our policy for teams is X" -- I believe @yifatdzigan had something on her slides during the section kick-off, which would fit there.

**Comment by svenvanderburg** [comment]
I have opened https://github.com/alan-turing-institute/the-turing-way/issues/2207 for adding something to the Turing Way. @c-martinez what was the Github name of the person you mentioned I should tag?

**Comment by c-martinez** [comment]
I've added a comment & tagged her on your turing way issue :-)
