### ISSUE TITLE
Java chapter is very outdated

### ISSUE THREAD

**Issue by cwmeijer** [NLeSC/guide#257]
There have been no significant updates in the last 5 years.
After so much time, I doubt that it will teach anyone anything useful anymore. As I don't have the expertise or time to update it, I propose to remove the chapter all together from the guide to prevent the spread of misinformation.

**Comment by jmaassen** [comment]
From the looks of it, about 75% of the page is still valid. There are a few recommendations which are indeed outdated (bintray for example) and should be updated. Let's disable the reference for now until it's up to date again.

**Comment by cwmeijer** [comment]
What about merging the PR for now? That will remove the page, but it will still be in the history.

**Comment by jmaassen** [comment]
Sure. Sounds like a good solution until we can/want to update the page

**Comment by jmaassen** [comment]
To what extend are the other language guides okay? As far as I can tell, the C one is fine (not sure about C++). The FORTRAN one is a bit too opinionated for my taste.

**Comment by egpbos** [comment]
I did some suggestions for the Python chapter a while ago, but didn't have time to finish them. I will have another go at it now.

**Comment by egpbos** [comment]
Python will again be up to date after merging #259, #260, #261, #262 and #263 😁
