### ISSUE TITLE
Language guides vs. templates

### ISSUE THREAD

**Issue by egpbos** [NLeSC/guide#265]
While discussing #260, I realized that we're duplicating language documentation between the Python language chapter and our [Python template](https://github.com/nlesc/python-template). For instance, I recently added `tox` support there, including explanation of why `tox` is a good alternative to just vanilla `pytest`. It feels foolish to have to add it here as well.

This got me thinking: isn't having templates a better, more active and constructive way to convey our best practices anyway? Shouldn't we simply convert all information in the language chapters into directly practically applicable templates? And then just keep those up to date.

**Comment by c-martinez** [comment]
Hey @egpbos -- I agree we should not duplicate efforts, but just having our best practices shared in the templates implies that we always create a new project (so we exclude out all existing software from being able to improve).

I think it might be a better approach to NOT include the reasoning in the template, but rather point to the guide (or The Turing Way if suitable).
