### ISSUE TITLE
Calling cffconvert

### ISSUE THREAD

**Issue by kretep** [NLeSC/guide#276]
Not sure what version of cffconvert is referred to here:
https://github.com/NLeSC/guide/blob/6cfc7be5afacab0f78314880a239bf644d203264/citable_software/making_software_citable.md?plain=1#L42

The command that works for me is
`cffconvert --format zenodo --outfile .zenodo.json`

**Comment by BSchilperoort** [comment]
This guide might be outdated, as I am under the impression that Zenodo supports the `CITATION.cff` file.

To quite from the [citation-file-format repository](https://github.com/citation-file-format/citation-file-format):
> When you publish your software on Zenodo via the [GitHub-Zenodo integration](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content), they will use the metadata from your CITATION.cff file.

**Comment by jspaaks** [comment]
`--ignore-suspect-keys` is cffconvert pre 2.0.0, indeed the information is outdated

**Comment by kretep** [comment]
Good to know! By the way, I needed to perform an extra step to get Zenodo to list the repositories for the organization containing the repo: I had to set the organization's "Third-party application access policy" to "no restrictions". Is this something worth mentioning or am I missing something else?

**Comment by bouweandela** [comment]
Information on citing software is available in The Turing Way [here](https://the-turing-way.netlify.app/communication/citable/citable-cite#cm-citable-cite-software)and can be removed from the guide.
