### ISSUE TITLE
Example for different topics

### ISSUE THREAD

**Issue by cpranav93** [NLeSC/guide#281]
It would be easier for someone reading the guide if we could create a example project (on github) and walk them through this for different aspects of best practices (licensing, issues, PR, github pages, etc)

**Comment by bouweandela** [comment]
This would be a considerable maintenance burden for us though and it is quite generic, so maybe this would be more suitable for The Turing Way? Maybe there are existing examples?

**Comment by egpbos** [comment]
The [Python template](https://github.com/NLeSC/python-template) in a way does this, although specifically for Python. I agree it's a nice idea, but I would say it's a whole new project, outside of the direct scope of the Guide, mostly for the reasons @bouweandela mentions, i.e. maintenance burden. The Guide itself already has big maintenance issues.

That said, "maintenance burden" is partly guesswork. Why don't you try it @cpranav93? See how far you get and then we have an idea of how feasible it is.

In fact, I think this could be a nice little project to work out together with a few other RSEs. If you would like to do it like that, I will announce in a LLT on 23 November a new periodic activity focused on software quality. This idea would be a perfect candidate for that... Sorry for the vagueness, DM me if you want more details.

**Comment by egpbos** [comment]
If someone wants to pick this up, feel free to reopen.
