### ISSUE TITLE
Remove outdated content

### ISSUE THREAD

**Issue by bouweandela** [NLeSC/guide#286]
Much of the content of the guide is outdated and/or has been moved to The Turing Way. I will make a start with removing this content, as it reflects poorly on the center.

**Comment by egpbos** [comment]
When we are done with this issue, we may need to remove the sentence that may be added through #285 about the outdated sections ;)

**Comment by egpbos** [comment]
Things to remove:

- Checklist: remove completely.
- Version control: Policy -> PMP, "we use GitHub" as well.
- Code quality
- Code reviews
- Licensing: "we use Apache v2" -> PMP. Rest is in Turing Way.
- Communication: already in PMP: output management.
- Testing
- Releases
- Documentation: update & move to Turing Way.
- Standards: not really stressed in the Turing Way. Make issue there? Connect to code quality, mention FAIR. There's something about data standards. In Code Quality there's style standards. Should be more stressed: interoperability & reusability by using standards.
- Teamwork
- NLeSC specific stuff: only keep chapter owners in chapters themselves
- Intellectual property: -> PMP

Keep:

- UX
- Language guides: need update!

Add:

- Julia
- Rust
- Matlab?
- Go?
- Look into https://softwaresaved.github.io/international-survey-2022/country/world/#tools-and-programming-languages
- ML guide?

**Comment by LourensVeen** [comment]
I think IP already went to the Turing Way, and anyway we have our IP Policy. Does that leave anything for the PMP?

**Comment by egpbos** [comment]
Yes, you're right, thanks!

**Comment by egpbos** [comment]
One part of the e-infrastructure Guide that may be useful to keep is https://guide.esciencecenter.nl/#/nlesc_specific/e-infrastructure/e-infrastructure?id=security-and-convenience-when-committing-code-to-github-from-a-cluster, what do you think @bouweandela @c-martinez? Not sure where to put it, though.

**Comment by egpbos** [comment]
I will open a separate issue for this.

**Comment by egpbos** [comment]
See also #335

**Comment by PabRod** [comment]
In order to facilitate this task and make it more parallelizable, I suggest to redo [the original task list](https://github.com/NLeSC/guide/issues/286#issuecomment-1789054656) following this structure:

## For straightforward replacements
- [ ] Material to be removed (linked) --> Link to replacement

## For replacements spread among many links:
- [ ] Material to be removed (linked) --> Link one
- [ ] .................................................. --> Link two

## For non-replacements
Any tasks including _keep_, _add_ or _update_ don't belong here.

What do you think, @egpbos, @bouweandela?

**Comment by egpbos** [comment]
I will pick this up now.

**Comment by egpbos** [comment]
## Straightforward replacements

Materials that were moved to the Turing Way that we want to map (using links to the Turing Way or RSQkit or other reputable sources) in the Best Practices chapter (see #321 and #360).

- [ ] Checklists
    - [ ] Add a section to Best Practices; the [PR where it was removed](https://github.com/NLeSC/guide/pull/294) contains links.
    - [x] Remove the chapter [PR](https://github.com/NLeSC/guide/pull/294)
    - [x] Afterwards: check for broken links (globally! the PR link checker only checks changed files...)
- [ ] Version control
    - [ ] Add a section to Best Practices.
        - [ ] NLeSC-internal note: refer to the PMP, "we preferably use GitHub".
    - [x] Remove the chapter [PR](https://github.com/NLeSC/guide/pull/313)
    - [x] Afterwards: check for broken links (globally! the PR link checker only checks changed files...)
- [ ] Code quality
    - [ ] Add a section to Best Practices.
    - [ ] Remove the chapter
    - [ ] Afterwards: check for broken links (globally! the PR link checker only checks changed files...)
- [ ] Code reviews
    - [ ] Add a section to Best Practices.
    - [ ] Remove the chapter
    - [ ] Afterwards: check for broken links (globally! the PR link checker only checks changed files...)
- [ ] Licensing
    - [ ] Add a section to Best Practices.
        - [ ] NLeSC-internal note: refer to the PMP, "we preferably use Apache v2".
    - [x] Remove the chapter [PR](https://github.com/NLeSC/guide/pull/296)
    - [x] Afterwards: check for broken links (globally! the PR link checker only checks changed files...)
- [ ] Communication
    - [ ] Add a section to Best Practices.
        - [ ] NLeSC-internal note: refer to the PMP, section "output management"
    - [x] Remove the chapter [PR](https://github.com/NLeSC/guide/pull/314)
    - [x] Afterwards: check for broken links (globally! the PR link checker only checks changed files...)
- [ ] Testing
    - [ ] Add a section to Best Practices.
    - [x] Remove the chapter [PR](https://github.com/NLeSC/guide/pull/315)
    - [x] Afterwards: check for broken links (globally! the PR link checker only checks changed files...)
- [ ] Releases
    - [ ] Add a section to Best Practices.
    - [ ] Remove the chapter
    - [ ] Afterwards: check for broken links (globally! the PR link checker only checks changed files...)
- [ ] Teamwork
    - [ ] Add a section to Best Practices.
    - [x] Remove the chapter [PR](https://github.com/NLeSC/guide/pull/295)
    - [x] Afterwards: check for broken links (globally! the PR link checker only checks changed files...)
- [ ] Intellectual property
    - [ ] Add a section to Best Practices.
        - [ ] NLeSC-internal note: refer to the PMP, section "IP policy"
    - [x] Remove the chapter: [PR together with licensing](https://github.com/NLeSC/guide/pull/296)
    - [x] Afterwards: check for broken links (globally! the PR link checker only checks changed files...)

## Non-replacements
Any tasks including _keep_, _add_ or _update_ don't belong here, but in their own issues.

- [ ] Documentation chapter: update & move to Turing Way.
    - [ ] Add a section to Best Practices.
    - [ ] Remove the chapter
    - [ ] Afterwards: check for broken links (globally! the PR link checker only checks changed files...)

- [ ] Standards chapter: not really stressed in the Turing Way. Make issue there? Connect to code quality, mention FAIR. There's something about data standards. In Code Quality there's style standards. Should be more stressed: interoperability & reusability by using standards.
    - [ ] Add a section to Best Practices.
    - [ ] Remove the chapter
    - [ ] Afterwards: check for broken links (globally! the PR link checker only checks changed files...)


### Add?

- [ ] Julia?
- [ ] Rust?
- [ ] Matlab?
- [ ] Go?
- [ ] Look into https://softwaresaved.github.io/international-survey-2022/country/world/#tools-and-programming-languages
- [ ] ML guide?

**Comment by egpbos** [comment]
Ok, I was hoping the above list would be auto-convertible to issues, but seems that doesn't work :(

**Comment by egpbos** [comment]
Done! Everything moved to other issues now. Closing this one.
