### ISSUE TITLE
Link checker is failing

### ISSUE THREAD

**Issue by lyashevska** [NLeSC/guide#291]

**Comment by egpbos** [comment]
It wasn't fixed after all :( There are still 19 other broken links, it seems...

By the way, I noticed that also #-links may be outdated. Not sure if the link checker checks for that (or if it even can).

cc @hanneoberman who tried valiantly to fix it in #292

**Comment by egpbos** [comment]
Btw, I was trying to have a go at this myself as well on Friday, but I got stuck in a side track when I tried to make a conda-forge package out of Lychee, the link checker we use and this week I don't have time.

**Comment by egpbos** [comment]
I fixed the output in #298, someone please approve it so we can see the list of failing links again :)

**Comment by egpbos** [comment]
All broken links now have separate issues or PRs to handle them: #286 will remove some chapters with broken links and #299, #300, #301, #302, #305, #306 and #307 should fix links in the remaining chapters.

**Comment by lyashevska** [comment]
great, lots of new issues :)

**Comment by egpbos** [comment]
Almost there! :D
