### ISSUE TITLE
Broken links in OpenCL & CUDA chapter

### ISSUE THREAD

**Issue by egpbos** [NLeSC/guide#299]
@isazi could you have a look at these broken links? Should they be replaced or removed?

* [404] [http://docs.nvidia.com/cuda/nvgraph/index.html](http://docs.nvidia.com/cuda/nvgraph/index.html) | Failed: Network error: Not Found
* [404] [http://docs.nvidia.com/cuda/cuda-memcheck/index.html](http://docs.nvidia.com/cuda/cuda-memcheck/index.html) | Failed: Network error: Not Found

**Comment by isazi** [comment]
Will do, thanks for letting me know.
