### ISSUE TITLE
OpenCL is dead

### ISSUE THREAD

**Issue by LourensVeen** [NLeSC/guide#303]
OpenCL is dead and nVidia is slowly getting some competition in the compute space so that CUDA doesn't really suffice anymore either. There's a whole bunch of potential alternatives (SYCL, Vulkan, HIP, OneAPI, OpenAcc, Kokkos, and probably more I don't know about) but what to do? I think the CUDA and OpenCL chapter could use an update. Maybe something for the GPU SIG to pick up?

**Comment by isazi** [comment]
According to the people at Khronos OpenCL is not dead, it is widely used (especially on mobile) and it is the target of e.g. various SyCL compilers :)
I became the maintainer of that page yesterday, will allocate time before the end of the year for a thorough overhaul of our GPU guidelines.

**Comment by LourensVeen** [comment]
According to AMD it is though. At least they're not making a driver for the GPU in my laptop...

Anyway, you know much more about this than I do, so I'm looking forward to the new page. Thanks in advance!
