### ISSUE TITLE
Update actions in CI workflow

### ISSUE THREAD

**Issue by egpbos** [NLeSC/guide#304]
@bouweandela reported in #298: _I did notice rather a lot of deprecation warnings in the output where it actually checked the links though, maybe it's time we update the version of some of these actions?_

Indeed, mostly jitterbit is complaining a lot.

Let's just update all of them to the latest versions.

**Comment by bouweandela** [comment]
We should probably set up dependabot to update the actions automatically: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

**Comment by egpbos** [comment]
Some steps of the pdf workflow were updated in #393.

**Comment by egpbos** [comment]
Dependabot ran and showed no further necessary updates, so this is now done and handled, nice!
