### ISSUE TITLE
RStudio has become Posit

### ISSUE THREAD

**Issue by egpbos** [NLeSC/guide#307]
https://posit.co/blog/rstudio-is-becoming-posit/

Should we rename all RStudio references in the R chapter?

At least one link is reporting a 403 error, i.e. "access forbidden", the https://support.rstudio.com/hc/en-us/articles/205612627-Debugging-with-RStudio debugging link at the bottom of the article. In my browser it simply redirects to the new URL under the posit.co domain. I guess all links to rstudio.com should then be changed to posit.co URLs?

@maltelueken what do you think, does it make sense to rename? How did the R community respond to this name change? Would you have time to do a quick sweep of the chapter for these references?

**Comment by maltelueken** [comment]
I didn't find any broken links yet, but I will do a sweep to update the links which are now forwarded to posit.co. The IDE is still called RStudio so I don't think we need to rename anything since we are referencing the IDE and not the company behind it.

**Comment by egpbos** [comment]
To clarify: the link I mention indeed doesn't seem to be broken for normal users using normal browsers, but the link checker GitHub Action does report it broken. My guess is that posit maybe blocks requests from GH Action servers or perhaps that Lychee (the link checker) doesn't know how to redirect, like normal browsers do. Either way, the rstudio.com links all redirect to posit.co, so probably just a find-and-replace on that would make sense anyway :)

Thanks for picking this up!

By the way, I think it would also make a lot of sense if you put your name at the top of the chapter as its maintainer!
