### ISSUE TITLE
Add information on type hints to Python chapter

### ISSUE THREAD

**Issue by bouweandela** [NLeSC/guide#310]
I noticed that there is no information on type hints in the Python chapter. Would you have time to add this @egpbos?

**Comment by egpbos** [comment]
Not right now. I also wouldn't know what in particular to add, because my experience with it is limited. However, I'm sure there are useful things to say about mypy, maybe pydantic, or other aspects. If somebody else wants to pick this up, feel free!

**Comment by jiskattema** [comment]
Yeah for type hints!
Especially the automated tools can be (more) helpful if you provide some hints.
If you don't want to go all-out with hints, it still makes sense to add them to the public API of your code, to help others re-use it.
Adding an intro to type hints with some background is [here](https://realpython.com/python-type-checking/)
