### ISSUE TITLE
Python LSP language server

### ISSUE THREAD

**Issue by egpbos** [NLeSC/guide#317]
hi all! i'm not sure this is the right place, please let me know if not ;)
I'm using a language server whenever i can, and for python the best (only?) is [https://github.com/python-lsp/python-lsp-server](https://github.com/python-lsp/python-lsp-server)
This comes with its own choice for linter/formatter etc. I really recommend using an LSP to catch errors and find docs!

_Originally posted by @jiskattema in https://github.com/NLeSC/guide/issues/302#issuecomment-1795160001_

**Comment by jiskattema** [comment]
By [default](https://github.com/python-lsp/python-lsp-server#installation) the lsp server uses: rope, pyflakes, pycodestyle, autopep8/yapf, flake8, pylint.
There are a bunch of other options, but  python-lsp-server can work with Ruff [via a plugin](https://github.com/python-lsp/python-lsp-ruff).

**Comment by egpbos** [comment]
LSP is a great protocol, but it's a bit too implementation-detail-specific to be useful in a guide on research software engineering. I think it's enough for engineers to know that they linting is very helpful. What tool they use exactly is up to them, as long as it is a good editor with support for things like this.
