### ISSUE TITLE
Clarify difference of ruff vs black

### ISSUE THREAD

**Issue by bouweandela** [NLeSC/guide#318]
As far as I'm aware, Ruff can only correct small bits of lint, not full autofomatting..

_Originally posted by @bouweandela in https://github.com/NLeSC/guide/pull/302#discussion_r1383557698_

**Comment by egpbos** [comment]
"Full" autoformatting parity with black (and isort) was recently added: https://astral.sh/blog/the-ruff-formatter.

**Comment by egpbos** [comment]
It's officially still in beta, but it's already usable in the regular releases and given the pace of development I don't think it makes sense to wait for it to officially become stable, which will probably be in a month or so.
