### ISSUE TITLE
exclude support.posit.co domain from link checker

### ISSUE THREAD

**Issue by egpbos** [NLeSC/guide#319]
> Looking great! Unfortunate that the link is still failing. It seems we are not alone in this issue: https://community.rstudio.com/t/scraping-website-returns-403/133020/2
> 
> I think we should then simply put this domain on the exclude list for the link checker, I'll make a separate issue for that.
> 

_Originally posted by @egpbos in https://github.com/NLeSC/guide/pull/309#pullrequestreview-1717372944_

**Comment by bouweandela** [comment]
Done: https://github.com/NLeSC/guide/blob/8e33f5183a5d0107c883f92a9f619efdf3032a53/.github/workflows/link-checker-pr.yml#L38
