### ISSUE TITLE
Update Python Packaging section to use `pyproject.toml` instead of `setup.cfg`

### ISSUE THREAD

**Issue by sjvrijn** [NLeSC/guide#326]
Currently, the [Making an installable package](https://guide.esciencecenter.nl/#/best_practices/language_guides/python?id=making-an-installable-package) section of the Python guide still refers to `setup.cfg` as the main of two required files.

Since we've also moved away from `setup.cfg` in our [python cookiecutter template](https://github.com/NLeSC/python-template/pull/352), I think we should update the guide to match what we've currently implemented as best practice?

**Comment by egpbos** [comment]
In theory (and in practice, see e.g. https://github.com/NLeSC/python-template/issues/328), we could also rewrite the setuptools parts a bit to make people aware of alternatives that we started using, i.e. hatch/hatchling.

**Comment by bouweandela** [comment]
Maybe we could replace that whole section by one or more links to tutorials/documentation pages? The topic is quite generic, so I would expect that good resources are available, and the current text is rather detailed and therefore likely to go out of date quickly.

**Comment by egpbos** [comment]
Sounds good to me.

**Comment by ofek** [comment]
Let me know if I can help with reviews (I maintain Hatch/Hatchling)!

**Comment by egpbos** [comment]
@sjvrijn Do you want to make a PR for this? :)
