### ISSUE TITLE
Front page

### ISSUE THREAD

**Issue by egpbos** [NLeSC/guide#330]
We got a tip from Communications:

> On the first page, in bold, it tells the audience to read the Turing Way instead. Most people might tune out immediately and do just that instead of exploring the website. It’s never really a good idea to direct visitors away from your site, especially on the landing page. We would recommend you highlight the differences between our guide and the Turing Way in a more balanced way.

I think I agree we could write this better. Suggestions?

**Comment by lyashevska** [comment]
I agree with this tip. This is what I did when I was reading the guide for the first time. Better to refer in relevant sections (not front page).
