### ISSUE TITLE
add preview functionality to PRs

### ISSUE THREAD

**Issue by egpbos** [NLeSC/guide#338]
Currently, contributors (and reviewers) are advised to spin up a webserver locally to check out whether their changes render properly. Obviously, nobody does this. I have seen other repos automatically spin up a netlify or similar free server to create a preview of the website and link to it in the PR. For the Guide, I think this could be done even simpler, because the Guide is static content, it doesn't need a complicated webserver. Anybody have ideas of how to make this happen? I think it would greatly smoothen the contribution process and improve reviews (surely my own, because I'm only now noticing rendering errors in #328 😉).

**Comment by sverhoeven** [comment]
I setup netlify for PRs in one of my repos see for example https://github.com/i-VRESSE/workflow-builder/pull/169 .  I am using the [Open Source team plan](https://www.netlify.com/legal/open-source-policy/)

**Comment by egpbos** [comment]
Maybe we can use this? https://github.com/rossjrw/pr-preview-action

**Comment by bouweandela** [comment]
I looked into that one, but my impression is that it commits all the previews to your default git branch, which doesn't seem desirable to me.

**Comment by egpbos** [comment]
If I'm not mistaken, Netlify now no longer charges you when you go over limits: https://www.netlify.com/blog/introducing-netlify-free-plan

At least I didn't fill out any billing information...

**Comment by egpbos** [comment]
Indeed, I think with the new plans this is no longer an issue @sverhoeven, see:

- https://docs.netlify.com/accounts-and-billing/billing-faq/#how-can-i-make-sure-i-never-get-charged
- https://docs.netlify.com/accounts-and-billing/billing-faq/#free-tier-limits
