### ISSUE TITLE
Add Matomo tracking

### ISSUE THREAD

**Issue by egpbos** [NLeSC/guide#341]
Following up on the discussion in #161, instead of Google Analytics, we should add Matomo tracking to the Guide. We also use Matomo for the corporate site and for the research software directory.

Veronica referred me to @ewan-escience who was able to give me an account on the RSD Matomo server. To enable Matomo tracking, we need to add a small piece of code in the rendered pages.

However, if we want to track, which uses cookies, we also need a cookie banner. So, two todo items in this issue:

- [ ] Figure out how to get a cookie wall and implement it. We could perhaps take inspiration from the RSD.
- [ ] Activate tracking, using the tracking code below (I'll update it if it becomes out of date, depending on fast someone will pick up this issue).

```html
<!-- Matomo -->
<script>
  var _paq = window._paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//matomo.research.software/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '5']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Matomo Code -->
```

**Comment by ewan-escience** [comment]
Related to tracking, and in the light of #161, can the `data-ga="UA-55088238-8"` code and the plugin `ga.min.js` be removed?`

**Comment by egpbos** [comment]
I will check whether they still work. I vaguely remember that we didn't update it recently after some old version API went offline. If they do, until we have Matomo, it may still be helpful to keep collecting there.

**Comment by egpbos** [comment]
GA actually still is working, so let's keep it in for now while we move over to Matomo.

**Comment by ewan-escience** [comment]
According to the documentation, you can also use [Matomo without consent or cookie banner](https://matomo.org/faq/new-to-piwik/how-do-i-use-matomo-analytics-without-consent-or-cookie-banner/). This does impact [the accuracy](https://matomo.org/faq/general/faq_156/). We might also need a [privacy policy](https://matomo.org/faq/general/faq_152/).
