### ISSUE TITLE
Python: preferred documentation style

### ISSUE THREAD

**Issue by jvdzwaan** [NLeSC/guide#35]
Dafne updated the Python section about documentation (thank you!), what needs to be added is advice on what documentation style to use for new projects. 

The choices are: NumPy style or Google style 

Do we have a preference? What are arguments for/against?

See https://github.com/NLeSC/guide/blob/update-python/languages/python.md#writing-documentation (branch update-python)

**Comment by sverhoeven** [comment]
+1 for Google style.
