### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by ewan-escience** [NLeSC/guide#353]
Should the guide have a [favicon](https://en.wikipedia.org/wiki/Favicon)? Maybe we can reuse the one from the corporate website (https://www.esciencecenter.nl/favicon.ico).

**Comment by egpbos** [comment]
I'm in favor.

**Comment by egpbos** [comment]
Maybe use a different color, purple perhaps?

**Comment by ewan-escience** [comment]
I guess we should ask communications.

**Comment by egpbos** [comment]
Works! 
<img width="228" alt="Scherm­afbeelding 2024-10-16 om 13 14 20" src="https://github.com/user-attachments/assets/c1c8877e-f628-4669-8266-ab305e24111a">
