### ISSUE TITLE
Broken links in GPU chapter

### ISSUE THREAD

**Issue by egpbos** [NLeSC/guide#355]
@isazi could you (or someone else) have a look at the following links in the GPU chapter?

> Errors in best_practices/language_guides/opencl_cuda.md
> 
> [403] https://www.intel.com/content/www/us/en/docs/onemkl/developer-reference-dpcpp/2024-0/fourier-transform-functions.html#GUID-BB8891E9-D3D3-40B9-BBB1-2390C4340CDA | Failed: Network error: Forbidden
> [404] https://rocm.docs.amd.com/projects/HIP/en/latest/.doxygen/docBin/html/modules.html | Failed: Network error: Not Found
> [403] https://www.intel.com/content/www/us/en/docs/onemkl/developer-reference-dpcpp/2024-0/blas-routines.html#GUID-F277361F-49BA-437B-8100-3D2B6BBC3CC1 | Failed: Network error: Forbidden
> [403] https://www.intel.com/content/www/us/en/docs/onemkl/developer-reference-dpcpp/2024-0/random-number-generators.html#GUID-FFC80D12-C323-4A9F-83E3-D0ACDB686876 | Failed: Network error: Forbidden
> [403] https://www.intel.com/content/www/us/en/docs/oneapi/programming-guide/2023-2/optimize-your-sycl-applications.html | Failed: Network error: Forbidden
> [403] https://www.intel.com/content/www/us/en/docs/onemkl/developer-reference-dpcpp/2024-0/sparse-blas-routines.html#GUID-7123D31B-9C7F-4BA7-9792-02A417293E60 | Failed: Network error: Forbidden

I think the Intel ones are outdated and can simply be replaced with updated versions. The AMD one I'm not sure of.

**Comment by isazi** [comment]
Cool, I will have a look at this

**Comment by egpbos** [comment]
I tried to update the Intel links, but it seems like Intel simply blocks traffic from GitHub CI. Will exclude them from the link checker actions.
