### ISSUE TITLE
Python: preferred testing library

### ISSUE THREAD

**Issue by jvdzwaan** [NLeSC/guide#36]
Currently, the preferred testing library for Python is nose. 

However, the nose website states:
`Nose has been in maintenance mode for the past several years and will likely cease without a new person/team to take over maintainership. New projects should consider using Nose2, py.test, or just plain unittest/unittest2.`

Do we need to update our preference?

**Comment by sverhoeven** [comment]
Yes, we should, seems pytest is the winner at the moment.

**Comment by mkuzak** [comment]
yes, working on PR for that :)
