### ISSUE TITLE
Best practices chapter

### ISSUE THREAD

**Issue by c-martinez** [NLeSC/guide#360]
The guide should include a chapter on good practices, such as documentation, testing, etc. This should point to existing resources in the guide, Turing Way, RSQKit, etc.

**Comment by egpbos** [comment]
In #286, a lot of pages were removed that covered this type of information which is now in either the Turing Way or will be part of RSQkit. I think the topics in the removal list are a good set of topics to cover in this new chapter. Indeed, let's try as much as possible to keep this chapter short and point to existing external resources for more info. Maybe just one sentence per topic followed by an external link or two?
