### ISSUE TITLE
Software documentation chapter

### ISSUE THREAD

**Issue by c-martinez** [NLeSC/guide#361]
As part of the Best practices chapter (#360) we should have a section on software documentation, pointing to https://github.com/the-turing-way/the-turing-way/pull/3768 (ideally, already merged)

**Comment by c-martinez** [comment]
https://book.the-turing-way.org/reproducible-research/code-documentation

**Comment by egpbos** [comment]
Awesome! Adding to best practices chapter will be tracked from #385.
