### ISSUE TITLE
Improve the PDF layout

### ISSUE THREAD

**Issue by vedran-kasalica** [NLeSC/guide#369]
The generated PDF layout is not ideal, and could be improved.

The titles start at the bottom of a page:
<img width="1106" alt="Screenshot 2024-12-03 at 11 54 35" src="https://github.com/user-attachments/assets/bc8a2b2a-c932-4477-a3a2-61660da4f3b1">

The table on page 56 is slightly broken:
<img width="1131" alt="Screenshot 2024-12-03 at 12 05 23" src="https://github.com/user-attachments/assets/9d970c8f-80e8-4e2b-b0e4-49beda6e588c">

**Comment by bouweandela** [comment]
> The table on page 56 is slightly broken:

That table looks like something that should be removed as part of #286. I'm not sure if it is relevant enough to port to The Turing way.

**Comment by vedran-kasalica** [comment]
> > The table on page 56 is slightly broken:
> 
> That table looks like something that should be removed as part of #286. I'm not sure if it is relevant enough to port to The Turing way.

I agree. Even if we remove this table, having a robust conversion that can convert tables without issues would be nice.
