### ISSUE TITLE
Python: choose recommended approach for building packages

### ISSUE THREAD

**Issue by jvdzwaan** [NLeSC/guide#38]

**Comment by sverhoeven** [comment]
To build a distribution the most common approach I have seen is to use `setup.py` with setuptools.
Use `python setup.py sdist` for pure Python packages or `python bdist_wheel` for others.
This will generate a tarball and *.whl file respectively in the dist/ directory.

Then uploading the package to pypi with [twine](https://pypi.python.org/pypi/twine).

**Comment by mkuzak** [comment]
I think this is most up to date guide:
https://packaging.python.org/

**Comment by mkuzak** [comment]
What about conda packages?

**Comment by sverhoeven** [comment]
Packaging your Python library as a Conda packages is needed when it depends on C-libraries. 

The pure Python packages and platform wheels can be installed in a Conda environment with pip.

**Comment by mkuzak** [comment]
@sverhoeven This information should be part of building packages description.

**Comment by jvdzwaan** [comment]
I remember @HannoSpreeuw promised to write something about conda

**Comment by HannoSpreeuw** [comment]
Well, Daniela and me volunteered to update the paragraph about Conda in the Python chapter of the NLeSC guide.
https://nlesc.gitbooks.io/guide/content/languages/python.html
I will try to do so this month.

**Comment by mkuzak** [comment]
Thank you @HannoSpreeuw 
that's vary much appreciated :)

**Comment by HannoSpreeuw** [comment]
But conda packaging seems to be covered already under
Building and packaging code ---> Build using conda

**Comment by mkuzak** [comment]
ok, maybe mentioning it's there would help

**Comment by HannoSpreeuw** [comment]
Okay, I will refer to it in the Conda section, which I am presently updating for another reason.

**Comment by HannoSpreeuw** [comment]
That's done. 

Let's get back to the original issue. 
According to this comparison
http://conda.pydata.org/docs/_downloads/conda-pip-virtualenv-translator.html
we should recommend conda for all of our packaging.

So conda should be our recommended build approach and not only for Python packages.

**Comment by jvdzwaan** [comment]
Well, I like about conda that you don't need admin rights...

Maybe we should recommend to do both conda and pip?

**Comment by c-martinez** [comment]
@jvdzwaan -- You don't need admin rights to install something via pip (at least not on a virtualenv)

@HannoSpreeuw -- the [comparison](http://conda.pydata.org/docs/_downloads/conda-pip-virtualenv-translator.html) shows you how to do equivalent command between conda and pip+virtualenv -- I don't think it indicates in any way that one is superior to the other.

I really liked [this post](https://jakevdp.github.io/blog/2016/08/25/conda-myths-and-misconceptions/) -- particularly Myth 10 -- we shouldn't focus on which one is better, but rather should make them more interoperable. In my opinion, a nicely written package should be available regardless of whether your user is going to pick one or the other.

**Comment by mkuzak** [comment]
There is also an issue about adding mentioned post, because it's very informative.

**Comment by c-martinez** [comment]
Adding it to the guide you mean? I think that is a good idea. I'll try to send a PR to the python chapter.

**Comment by LourensVeen** [comment]
You know, as flamewars go this one is pretty disappointing. I was all set with popcorn and everything, and now you're having a civilised discussion, with arguments and all...

My 2 cents: As a casual Pythonist, I find pip+virtualenv easier to remember than conda, being simpler. I'll happily put my stuff into both if that's what you recommend, but conda will take a bit more effort to read up on again.

**Comment by c-martinez** [comment]
@HannoSpreeuw is a reasonable man, so no need to go to war.

Packaging for both -- I will go with my favourite answer: it depends -- check what makes more sense for your package. If your package is 100% pure python, I would personally recommend to make it pip installable, and then conda users can also use it. If you have lots of external dependencies which are hard to compile, then go with conda. Use the force, and the right tool for the job.

**Comment by jvdzwaan** [comment]
Closing... :)
