### ISSUE TITLE
Documentation chapter

### ISSUE THREAD

**Issue by egpbos** [NLeSC/guide#385]
- [x] Update where necessary & move to Turing Way. #361
- [x] Add a section to Best Practices.
- [x] Remove the chapter
- [x] Afterwards: check for broken links (globally! the PR link checker only checks changed files...)

**Comment by bouweandela** [comment]
Duplicate of #361?

**Comment by egpbos** [comment]
Awesome, indeed! #361 covers task one in this issue. I will close that one and finish the rest of this one.
