### ISSUE TITLE
Python visualization: what do people think of plotly?

### ISSUE THREAD

**Issue by jspaaks** [NLeSC/guide#43]
https://plot.ly/

If we like it, we should add it to the list

**Comment by sverhoeven** [comment]
Have not used it myself.
It seems nice for in Jupyter notebooks.
For web applications it can be too restrictive (not extendable enough) and I would use d3 directly.

**Comment by c-martinez** [comment]
Plot.ly is already mentioned in the [Python chapter](https://guide.esciencecenter.nl/#/best_practices/language_guides/python?id=visualization).
