### ISSUE TITLE
Broken links in chapters

### ISSUE THREAD

**Issue by nielsdrost** [NLeSC/guide#69]
As per our shiny new broken link checker (see #24), we have a great overview of all the broken links in the guide. We should fix them :-)

See https://travis-ci.org/NLeSC/guide for an overview of all broken links.

Chapters with broken links atm:

- [ ] Software/Communication
- [ ] Software/Code Review
- [ ] Software/Documentation
- [ ] Languages/Java
- [ ] Languages/Javascript
- [ ] Languages/Python
- [ ] Languages/R
- [x] Contributing

Chapter owners, please fix :-)

**Comment by mkuzak** [comment]
I'm on it. I thought about fixing links in my part but when I'm doing it I can as well fix them for whole guide, no need for bothering all maintainers. @jspaaks @jvdzwaan @cwmeijer @vincentvanhees @LourensVeen

**Comment by mkuzak** [comment]
@nielsdrost any idea where this should point? .editorconfig?

```
See the collection of config files for automated coding style [here](https://github.com/NLeSC/knowledge/tree/master/software/config)
```

**Comment by mkuzak** [comment]
@LourensVeen from code review chapter:

> - Klocwork (http://www.klocwork.com/Code-Review-Tools)
>    - Link dead, doesn't appear to offer any code review tools

I don't think it make sense to include in the guide something which seams to be dead.
The point of the guide is to give people useful readily applicable information.
Plus now that we check for dead links we should avoid having them on purpose.

**Comment by mkuzak** [comment]
@cwmeijer In java chapter:

> SonarQube (http://www.sonarqube.org/) is an open platform to manage code quality.
> On our Jenkins build server we do a SonarQube analysis for each Jenkins job. Out SonarQube > instance is hosted at https://sonar.esciencecenter.nl and is behind a login.
> Sonar Qube can analyze Java, Python and Javascript.

It looks like there is no sonar hosted by us any more.

**Comment by cwmeijer** [comment]
Just to be sure, let's ask @sverhoeven :-) Do we still have any SonarQube installation running that should be mentioned in the Java guide?

**Comment by cwmeijer** [comment]
Just heard from @nielsdrost that we don't have SonarQube installed anymore. I'll update the guide.

**Comment by sverhoeven** [comment]
That is correct we are not running our own SonarQube and Jenkins server anymore.

**Comment by nielsdrost** [comment]
> @nielsdrost any idea where this should point? .editorconfig?

The java code style is already referred to from the Java Chapter. The editorconfig is mentioned and linked to one paragraph above the broken link. So I vote we remove the whole sentence.

**Comment by mkuzak** [comment]
done

**Comment by sverhoeven** [comment]
@jspaaks The link to http://localhost:8000 on the javascript page should be excluded from the checker by adding `--exclude localhost:8000` to the `blc` command in `.travis.yml` file.
