### ISSUE TITLE
Link to emergency revert for accidentally uploaded confidential data

### ISSUE THREAD

**Issue by mkuzak** [NLeSC/guide#7]
By @egpbos 

> In case the code uses data, that cannot be open, an engineer should try to keep sensitive parts outside of the main codebase.

It sometimes happens that sensitive data is accidentally uploaded. It would be nice if the checklist has an emergency _get that stuff out of my history_ guide (or link to separate guide, e.g. this one https://help.github.com/articles/remove-sensitive-data/).

comments:
By @mkuzak
Agreed, this is important to have, but should go to documentation.
Actual solution should not be in the checklist, but we should add a note how to prevent (adding things to .gitignore).

**Comment by bouweandela** [comment]
The link is already in the repository: https://github.com/NLeSC/guide/blob/master/software/version_control.md#repositories-should-be-public
New issue on how/why not to upload large data files: #143
