### ISSUE TITLE
Best and Good Enough practices in scientific computing

### ISSUE THREAD

**Issue by nielsdrost** [NLeSC/guide#70]
Our guide is all about best practices. However, there is also such a thing as "good enough".

These two (known) sources are great in explaining these:

Good Enough Practices in Scientific Computing https://arxiv.org/abs/1609.00037
Best Practices in Scientific Computing http://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1001745

We should at least link to these somewhere. I propose to do this in the introduction of the software guide (which is currently a single sentence, so could use some more content anyway)

**Comment by bouweandela** [comment]
This content would be more appropriate for The Turing Way
