### ISSUE TITLE
Tools of the Trade chapter?

### ISSUE THREAD

**Issue by nielsdrost** [NLeSC/guide#71]
I recently discovered https://draw.io as a really nice way of drawing diagrams. I of course instantly though about adding this to the guide!

However, we seem to not have a section for this. :-(

Do we need a new chapter for this? I can image things like Overleaf, SURFdrive, and Figshare, all deserve a mention somewhere in the guide.

**Comment by mkuzak** [comment]
Interesting. The question is if maybe they should be mentioned in the context of function. For example Figshare in the context of data repositories and where to store data that is part of the project.

**Comment by bouweandela** [comment]
This content would be more appropriate for The Turing Way
