### ISSUE TITLE
Nicer landing page

### ISSUE THREAD

**Issue by tbkkr** [NLeSC/guide#74]
Would it be worth to put some effort into making a nicer landing page (https://guide.esciencecenter.nl/index.html)? Or at least one with somewhat more clear information as to what one can find in the guide, for who the guide is (us, RSEs, PI’s, project members? all?), how one can give input/suggestions, and what the goal of the guide is?

**Comment by nielsdrost** [comment]
Yes, definitely!

Note that this is the introduction chapter of a book, rather than the front page of a website.

**Comment by egpbos** [comment]
Definitely a great idea. PRs welcome! Since 6,5 years is quite stale as far as issues go, I will close this one now ;)
