### ISSUE TITLE
Permanent search bar

### ISSUE THREAD

**Issue by tbkkr** [NLeSC/guide#77]
I only found out today that there is a search option. How about making it better (=permanent) visible? That really helps people getting to their goal quicker. Here's an example of how did they that: https://componently.github.io/componently/.

**Comment by nielsdrost** [comment]
I think this is due to us using the "old" GitBook version 2.* instead of the "new" Gitbook, which had a problem with chapter numbering at the time. Will try updating, and see if anything breaks/improves.

**Comment by bouweandela** [comment]
Is this still relevant? At the moment, the search box is still not permanently visible on our page, but that appears to be mostly because our table of contents is too large to fit in the side bar. The example has a much shorter table of contents.

**Comment by bouweandela** [comment]
Reaction from @tbkkr by email:

> Misschien even kijken naar V2 van Gitbook, want draaien wij niet nog steeds de oude versie? Volgens mij is de search function wat aangepast in nieuwe versie van gitbook.
> 
> wb de ToC links: die moet misschien wat korter, bv:
>
>   2.1 > onderbrengen bij 2.7
    2.8 en 2.9 ook ondebrengen bij 2.7 wellicht Bij IP & Licences zou ik vooral Licences neerzetten.
    2.3 en 2.4 samen
    2.6 en 2.7 samen
    3.1 > kan weg?

**Comment by bouweandela** [comment]
The search bar is indeed part of newer versions, but the problem is that chapter numbering is ugly in newer versions of gitbook, see e.g. https://github.com/GitbookIO/gitbook/issues/1301. If we want the search bar, we should disable numbering the chapters in the table of contents or wait for gitbook to fix the issue.

**Comment by bouweandela** [comment]
I discussed with @lodekulik and he advised that it is fine to drop the chapter numbers as is the default in newer gitbook versions. Therefore I think we can safely upgrade to the latest version.

**Comment by bouweandela** [comment]
I have switched to the version 3 builder, which should solve this issue.

**Comment by bouweandela** [comment]
Except that the search bar still disappears if you scroll down too far. So we need to reduce the number of chapters.

**Comment by egpbos** [comment]
This discussion is outdated. We no longer use GitBook, but docsify. I have briefly looked into how to fix this issue, but cannot find a default option, even though [here](https://github.com/docsifyjs/docsify/issues/903) it is suggested that placing the search bar elsewhere is possible, but not without significant effort and the maintainability issues that brings.

If someone wants to open a PR to make the search bar permanently visible (and retains all other functionality), most welcome! This issue, in the meantime, can be closed.
