### ISSUE TITLE
copyright notice/disclaimer at the top of every source code file

### ISSUE THREAD

**Issue by mkuzak** [NLeSC/guide#8]
By @mkuzak
I'm in favor of getting rid of those, since they are not required. Unless someone thinks we need it.
# comments

By @sverhoeven 
If the source code file is or can be distributed alone then the notice should be there.
If the source code file is always distributed with a LICENSE file, etc. then the notice can be removed.
@LourensVeen what do you think?

---

By @jiskattema 
if i remember correctly, they are not (legally) necessary
How about only leaving them in if the license is not our preferred license, and redistribution is likely?

---

By @mkuzak
I agree with @sverhoeven on that, if the files are likely to be distributed separately they should have notice on top, otherwise not.

---

By @LourensVeen
It's not legally necessary. When you create a work you get to own the copyright, whether you put any notices on it or not (according to the Berne convention, which almost all nations are signatory to). If you don't have a statement in every file and somehow a file gets separated from the rest, then whoever gets it would not know that it's licensed, and therefore should not distribute it. If they can somehow ascertain that it's ASLv2, then they can safely distribute it, as long as they put the license notice back in, since the license requires that.

Of course, having such a notice prevents a lot of hassle in such a case, but I agree that in practice this probably doesn't happen often, and especially in short files it's not nice to have such a big block of text repeated everywhere.

Both the FSF and the ASF recommend putting a rather lengthy notice into every file, with a restatement of the warranty disclaimer. I've never heard of anyone suing anyone over a warranty issue with free software however, and I can't imagine a judge ruling that we're responsible for warranty on a free-of-cost piece of software licensed under a license that explicitly disclaims warranty, just because it wasn't restated in every single file. (If someone pays us to develop software for them, then we will probably be required to provide warranty regardless of what the license says, but that's a separate issue.)

Perhaps we can use a shortened version, something like this:

Copyright 2014, 2016 Netherlands eScience Center.
Licensed under the Apache License, version 2.0. See LICENSING for details.

The LICENSING file could then contain the longer statement, together with the actual license text, or something more complicated if the program consists of multiple modules with different licenses.

Anyone wanting to reuse a single file from our program would then be responsible for doing so according to the license, e.g. by having their own LICENSING file that explains that we own that particular file and contains the license, or by adding the longer statement to the file, or in some other way that the license we used allows.

Since there is at least a statement of who owns the copyright, if someone happens to come across a single file, they at least know that it's copyrighted (and can't claim they thought it was public domain) and they can contact us if there's any doubt as to what happened and what they are and aren't allowed to do.

---

By @larsmans
Agree with @LourensVeen on including that short notice. Program modules get copied around when users want only part of the functionality.

---

By @mkuzak
What will we do in case of files with external contributions. We'd have to ask people to transfer their copyrights to NLeSC. We should have some standard form for that too

---

By @LourensVeen
Not necessarily, the copyright could be shared. The contributors do have to explicitly contribute under Apache 2.0, but the license already contains language that says that all contributions are considered to be under Apache 2.0 as well.

Of course, this will make it more difficult to relicense the code, because all contributors have to give permission. This is more of a governance matter than a licensing matter though.

**Comment by jvdzwaan** [comment]
What to do in case of existing code with existing copyright lines? Do we need to add our own line? Depending on the software license of the existing code? 

(This is not a hypothetical situation, I am adapting code licensed under BSD clause 2 at the moment.)

**Comment by LourensVeen** [comment]
Ah, good question. If you're modifying an existing file with an existing license, then there should only be an additional copyright line I'd say, but with the original copyright statement. So we'll use the existing license for our additions. I've added a note to #82.

**Comment by Kendee** [comment]
OK, here is my BIG problem with copyright lines (and version info too!) in every file.

When a new version of the project is issued, then every file in the project is changed if the copyright year (or from .. to years) is being kept up to date. This makes change tracking a nightmare.

About once a year I get updates sources for one project which has about 250 files in it and I cannot see what functionality has changed without a great deal of effort! Usually it is one or two files whose constant values have changed (I know, changing constants - yeah!).

It the copyright notice really worth all that hassle?

**Comment by mkuzak** [comment]
As long as only the copyright lines are changed in the commit and the commit has the appropriate message, I don't see an issue there.

**Comment by Kendee** [comment]
Yes, one work around is to change the copyright/version info for all files in one commit (with the appropriate commit message) and make functional changes in a separate commit (or commits). But isn't it easier to just not have license and version info in there in the first place?

**Comment by mkuzak** [comment]
I don't believe this is a workaround. Those should not be in the single commit in the first place. Functional changes **should not be mixed** with copyright/version info update.

**Comment by Kendee** [comment]
Agreed!

**Comment by c-martinez** [comment]
This is an old issue and the discussion has gone stale -- closing this issue, please reopen it if relevant.
