### ISSUE TITLE
 GPGPU

### ISSUE THREAD

**Issue by nielsdrost** [NLeSC/guide#83]
via @isazi 

Prace has released a best practices GPGPU guide.

Would it make sense to link to this in the OpenCL/Cuda section of the guide?

http://www.prace-ri.eu/best-practice-guide-gpgpu-january-2017/
http://www.prace-ri.eu/IMG/pdf/Best-Practice-Guide-GPGPU-1.pdf

**Comment by benvanwerkhoven** [comment]
Sure, it looks very similar to the CUDA programming guide with a few extras. A link has been added: 5115d1eca6c9a73bca346f2e07c9395ec3c71967
