### ISSUE TITLE
Java integration tests

### ISSUE THREAD

**Issue by sverhoeven** [NLeSC/guide#90]
Use docker-compose junit rule, https://github.com/palantir/docker-compose-rule
Use system-rules to capture stdout, etc, http://stefanbirkner.github.io/system-rules/index.html
See example https://github.com/NLeSC/xenon-cli/blob/master/src/test/java/nl/esciencecenter/xenon/cli/SlurmTest.java

Also mocked web services using http://wiremock.org/docs/junit-rule/
See example https://github.com/3D-e-Chem/knime-kripodb/blob/master/tests/src/java/nl/esciencecenter/e3dchem/kripodb/ws/JavaWsWorkflowTest.java

**Comment by bouweandela** [comment]
The Java chapter has been removed because it was too outdated.

**Comment by egpbos** [comment]
Note that we have a running KD project that may add it again, but in updated form. Looking forward to the PR @lyashevska, @bakhshir, @jmaassen, @nielsdrost, et al.(?) 😄
