### ISSUE TITLE
Project name spaces

### ISSUE THREAD

**Issue by sverhoeven** [NLeSC/guide#98]
At https://github.com/NLeSC/guide/blob/master/software/code_quality.md#name-spaces it says to use ` nl.esciencecenter`.

For projects I would like suggest to use the GitHub organization domain. 

For example for the [3D-e-Chem project](https://3d-e-chem.github.io/) the name space could be `3d-e-chem.github.io`

**Comment by mkuzak** [comment]
I agree, this is more in line with project centred vs Center centred.

**Comment by bouweandela** [comment]
The linked chapter is no longer in the guide.
